Though, aclocal normally comes with automake we should require it as well.
git-svn-id: https://svn.aros.org/svn/aros/trunk@29084 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3738,7 +3738,7 @@ aros_host_incl="/usr/include"
 aros_host_exe_suffix="$EXEEXT"
 aros_host_lib_suffix=""
 
-for ac_prog in aclocal aclocal19
+for ac_prog in aclocal aclocal19 aclocal-1.9
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -3906,6 +3906,12 @@ fi
   test -n "$aros_host_automake" && break
 done
 
+
+if test "$aros_host_aclocal" = ""; then
+    { { echo "$as_me:$LINENO: error: aclocal/aclocal19/aclocal-1.9 is required to build AROS. Please install and run configure again." >&5
+echo "$as_me: error: aclocal/aclocal19/aclocal-1.9 is required to build AROS. Please install and run configure again." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test "$aros_host_automake" = ""; then
     { { echo "$as_me:$LINENO: error: automake/automake19/automake-1.9 is required to build AROS. Please install and run configure again." >&5
 echo "$as_me: error: automake/automake19/automake-1.9 is required to build AROS. Please install and run configure again." >&2;}
