Disabled "differ in signedness" warnings by adding -Wno-pointer-sign option to aros_config_cflags if target compiler supports it.
git-svn-id: https://svn.aros.org/svn/aros/trunk@30013 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9276,6 +9276,64 @@ if test "$cross_compiling" = "yes" ; then
     CC=${target_tool_prefix}gcc
 fi
 
+#-----------------------------------------------------------------------------
+
+# Disable pointer-signedness warnings if the compiler recognises the option
+
+{ echo "$as_me:$LINENO: checking whether ${CC} accepts -Wno-pointer-sign" >&5
+echo $ECHO_N "checking whether ${CC} accepts -Wno-pointer-sign... $ECHO_C" >&6; }
+save_cflags="$CFLAGS"
+CFLAGS="$CFLAGS -Wno-pointer-sign"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  use_no_sign_warning="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	use_no_sign_warning="no"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $use_no_sign_warning" >&5
+echo "${ECHO_T}$use_no_sign_warning" >&6; }
+if test "x-$use_no_sign_warning" = "x-yes" ; then
+    aros_config_cflags="$aros_config_cflags -Wno-pointer-sign"
+fi
+CFLAGS="$save_cflags"
+
+#-----------------------------------------------------------------------------
+
 # Find all the tools we need to compile. This could be cross-compiling
 # though! If that is the case we use the GNU form of the target and
 # simply add this to the front of the binary name. This is rather simple,
