detect and setup mingw32 environment (patch from Carlo Bramini)
git-svn-id: https://svn.aros.org/svn/aros/trunk@27588 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4061,6 +4061,21 @@ echo "$as_me: WARNING: \"Unknown CPU for host -- $host_cpu\"" >&2;}
 		;;
 	esac
         ;;
+
+    mingw32*)
+        aros_host_arch="mingw32"
+	aros_host_cc="$aros_host_cc $aros_host_cc_pipe"
+	case "$host_cpu" in
+	    *i?86*)
+		aros_host_cpu="i386"
+		;;
+	    *)
+		{ echo "$as_me:$LINENO: WARNING: \"Unknown CPU for host -- $host_cpu\"" >&5
+echo "$as_me: WARNING: \"Unknown CPU for host -- $host_cpu\"" >&2;}
+		aros_host_cpu="$host_cpu"
+		;;
+	esac
+        ;;
     *)
 	{ { echo "$as_me:$LINENO: error: Unsupported host architecture $host" >&5
 echo "$as_me: error: Unsupported host architecture $host" >&2;}
@@ -8418,6 +8433,27 @@ echo "$as_me: error: \"Unknown CPU for Amiga $target_cpu\"" >&2;}
 	    *)
 		{ { echo "$as_me:$LINENO: error: \"Unknown CPU for CygWin -- $target_cpu\"" >&5
 echo "$as_me: error: \"Unknown CPU for CygWin -- $target_cpu\"" >&2;}
+   { (exit 1); exit 1; }; }
+		;;
+	esac
+    ;;
+
+    mingw32*)
+        aros_target_arch="mingw32"
+	aros_shared_default="no"
+	case "$target_cpu" in
+	    *i?86*)
+		aros_target_cpu="i386"
+                aros_object_format="elf_i386"
+		aros_flavour="emulation"
+                aros_target_mkdep="$aros_target_mkdep -D__GNUC__ -Di386"
+		aros_shared_cflags=""
+		aros_default_wbdepth=8
+		gcc_target_cpu="i386"
+		;;
+	    *)
+		{ { echo "$as_me:$LINENO: error: \"Unknown CPU for Mingw32 -- $target_cpu\"" >&5
+echo "$as_me: error: \"Unknown CPU for Mingw32 -- $target_cpu\"" >&2;}
    { (exit 1); exit 1; }; }
 		;;
 	esac
