Added support for ARM iOS target
git-svn-id: https://svn.aros.org/svn/aros/trunk@34718 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -812,7 +812,6 @@ aros_host_sdl_libs
 aros_serial_debug
 aros_palm_debug_hack
 aros_nesting_supervisor
-aros_xcode_path
 aros_ios_platform
 aros_ios_version
 aros_ios_sdk
@@ -1452,8 +1451,15 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-gcc-version=VERSION
+                          Use gcc-VERSION for building AROS
   --with-optimization=FLAGS
                           Use optimization flags FLAGS (default=-O2).
+  --with-xcode=PATH       Specify XCode path for iOS targets
+                          (default=/Developer).
+  --with-ios-version=VERSION
+                          Specify minimum supported iOS version (default=2.0).
+  --with-ios-sdk=VERSION  Use iOS SDK version VERSION (default=4.1).
   --with-portssources=DIR Where to download sourcecode for external ports
   --with-bootloader=NAME  Use a specific bootloader
   --with-iconset=NAME     Use a specific Icon-set (default=Gorilla).
@@ -8316,6 +8322,20 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 #-----------------------------------------------------------------------------
+{ echo "$as_me:$LINENO: checking what specific gcc version to use" >&5
+echo $ECHO_N "checking what specific gcc version to use... $ECHO_C" >&6; }
+
+# Check whether --with-gcc-version was given.
+if test "${with_gcc_version+set}" = set; then
+  withval=$with_gcc_version; target_tool_version="$withval"
+else
+  target_tool_version="default"
+fi
+
+{ echo "$as_me:$LINENO: result: $target_tool_version" >&5
+echo "${ECHO_T}$target_tool_version" >&6; }
+
+#-----------------------------------------------------------------------------
 { echo "$as_me:$LINENO: checking what optimization flags to use" >&5
 echo $ECHO_N "checking what optimization flags to use... $ECHO_C" >&6; }
 
@@ -8336,6 +8356,50 @@ fi
 aros_config_cflags="$aros_config_cflags $optimization"
 { echo "$as_me:$LINENO: result: $optimization" >&5
 echo "${ECHO_T}$optimization" >&6; }
+
+#-----------------------------------------------------------------------------
+if test "$target_os" = "ios"; then
+
+{ echo "$as_me:$LINENO: checking XCode path" >&5
+echo $ECHO_N "checking XCode path... $ECHO_C" >&6; }
+
+# Check whether --with-xcode-path was given.
+if test "${with_xcode_path+set}" = set; then
+  withval=$with_xcode_path; aros_xcode_path="$withval"
+else
+  aros_xcode_path="/Developer"
+fi
+
+{ echo "$as_me:$LINENO: result: $aros_xcode_path" >&5
+echo "${ECHO_T}$aros_xcode_path" >&6; }
+
+{ echo "$as_me:$LINENO: checking for minimum supported iOS version" >&5
+echo $ECHO_N "checking for minimum supported iOS version... $ECHO_C" >&6; }
+
+# Check whether --with-ios-version was given.
+if test "${with_ios_version+set}" = set; then
+  withval=$with_ios_version; aros_ios_version="$withval"
+else
+  aros_ios_version="2.0"
+fi
+
+{ echo "$as_me:$LINENO: result: $aros_ios_version" >&5
+echo "${ECHO_T}$aros_ios_version" >&6; }
+
+{ echo "$as_me:$LINENO: checking what iOS SDK version to use" >&5
+echo $ECHO_N "checking what iOS SDK version to use... $ECHO_C" >&6; }
+
+# Check whether --with-ios-sdk was given.
+if test "${with_ios_sdk+set}" = set; then
+  withval=$with_ios_sdk; aros_ios_sdk="$withval"
+else
+  aros_ios_sdk="4.1"
+fi
+
+{ echo "$as_me:$LINENO: result: $aros_ios_sdk" >&5
+echo "${ECHO_T}$aros_ios_sdk" >&6; }
+
+fi
 
 #-----------------------------------------------------------------------------
 { echo "$as_me:$LINENO: checking what target variant to enable" >&5
@@ -8573,11 +8637,6 @@ echo "$as_me: error: \"Unsupported target CPU for darwin hosted flavour -- $targ
 	;;
 
     ios*)
-        # TODO: these should be specified with arguments: --with-xcode, --with-ios-version, --with-ios-sdk
-	aros_xcode_path="/Developer"
-	aros_ios_version="2.0"
-	aros_ios_sdk="4.1"
-
 	aros_target_arch="ios"
 	aros_flavour="emulation"
 	# This is here because it may depend on iOS or SDK version
@@ -8587,8 +8646,6 @@ echo "$as_me: error: \"Unsupported target CPU for darwin hosted flavour -- $targ
 	    	aros_ios_platform="iPhoneSimulator"
 		aros_target_cpu="i386"
 		aros_target_mkdep="$aros_target_mkdep -D__GNUC__ -Di386"
-		aros_kernel_cflags="$aros_kernel_cflags -m32"
-		aros_kernel_ldflags="-m32"
 		aros_default_wbdepth=8
 		gcc_target_cpu="i386"
 		aros_object_format="elf_i386"
@@ -8604,6 +8661,29 @@ echo "$as_me: error: \"Unsupported target CPU for darwin hosted flavour -- $targ
 		aros_target_objcopy="i386-aros-objcopy"
 		aros_target_objdump="i386-aros-objdump"
 		target_tool_prefix="i686-apple-darwin10-"
+		target_tool_flags="-m32"
+		;;
+	    *arm*)
+	    	aros_ios_platform="iPhoneOS"
+		aros_target_cpu="arm"
+                aros_object_format="armelf_linux_eabi"
+                aros_target_mkdep="$aros_target_mkdep -D__GNUC__ -Darm"
+		aros_default_wbdepth=8
+		gcc_target_cpu="arm"
+		aros_kernel_ld="ld -arch armv6"
+		aros_target_cc="arm-elf-gcc"
+		aros_target_ld="arm-elf-ld"
+		aros_target_as="arm-elf-as"
+		aros_target_ar="arm-elf-ar"
+		aros_target_ranlib="arm-elf-ranlib"
+		aros_target_nm="arm-elf-nm"
+		aros_target_strip="arm-elf-strip"
+		aros_target_objcopy="arm-elf-objcopy"
+		aros_target_objdump="arm-elf-objdump"
+		target_tool_prefix="arm-apple-darwin10-"
+		aros_default_wbwidth=320
+                aros_default_wbheight=480
+                export PATH="$aros_xcode_path/Platforms/$aros_ios_platform.platform/Developer/usr/bin:$PATH"
 		;;
 	    *)
 		{ { echo "$as_me:$LINENO: error: \"Unsupported target CPU for iOS hosted flavour -- $target_cpu\"" >&5
@@ -8611,6 +8691,8 @@ echo "$as_me: error: \"Unsupported target CPU for iOS hosted flavour -- $target_
    { (exit 1); exit 1; }; }
 		;;
 	esac
+	aros_ios_sdk="$aros_xcode_path/Platforms/$aros_ios_platform.platform/Developer/SDKs/$aros_ios_platform$aros_ios_sdk.sdk"
+	target_tool_flags="$target_tool_flags --sysroot $aros_ios_sdk"
 	;;
 
     dragonfly*)
@@ -9042,7 +9124,56 @@ if test "$cross_compiling" = "yes" ; then
 	target_tool_prefix=${target_cpu}-elf-
     fi
     CC=${target_tool_prefix}gcc
+    if test "$target_tool_version" != "default"; then
+        CC="$CC-$target_tool_version"
+    fi
+    # Extract the first word of "$CC", so it can be a program name with args.
+set dummy $CC; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_CC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $CC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_CC="$CC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_CC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
 fi
+CC=$ac_cv_path_CC
+if test -n "$CC"; then
+  { echo "$as_me:$LINENO: result: $CC" >&5
+echo "${ECHO_T}$CC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    if test "$CC" = ""; then
+    { { echo "$as_me:$LINENO: error: gcc is required to build AROS. Please install and run configure again." >&5
+echo "$as_me: error: gcc is required to build AROS. Please install and run configure again." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+fi
+CC="$CC $target_tool_flags"
 
 #-----------------------------------------------------------------------------
 
@@ -12596,7 +12727,6 @@ echo "${ECHO_T}$dbus" >&6; }
 
 
 
-
 # DBUS related
 
 
@@ -13612,7 +13742,6 @@ aros_host_sdl_libs!$aros_host_sdl_libs$ac_delim
 aros_serial_debug!$aros_serial_debug$ac_delim
 aros_palm_debug_hack!$aros_palm_debug_hack$ac_delim
 aros_nesting_supervisor!$aros_nesting_supervisor$ac_delim
-aros_xcode_path!$aros_xcode_path$ac_delim
 aros_ios_platform!$aros_ios_platform$ac_delim
 aros_ios_version!$aros_ios_version$ac_delim
 aros_ios_sdk!$aros_ios_sdk$ac_delim
@@ -13631,7 +13760,7 @@ gcc_target_cpu!$gcc_target_cpu$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 22; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
