- Improved cross-compilation support in configure script - Fixed some issues popping up on gcc v4 - Fixed some C header issues
git-svn-id: https://svn.aros.org/svn/aros/trunk@30753 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -722,6 +722,7 @@ aros_target_objcopy_ln
 aros_target_objdump_ln
 aros_target_ranlib_ln
 aros_target_strip_ln
+aros_kernel_rescomp
 aros_target_nostdinc_cflags
 aros_target_nostartup_ldflags
 aros_target_nix_ldflags
@@ -8443,6 +8444,7 @@ echo "$as_me: error: \"Unknown native CPU -- $target_cpu\"" >&2;}
     darwin*)
 	aros_target_arch="darwin"
 	aros_flavour="emulation"
+					need_dlopen="no"
 	case "$target_cpu" in
 		*i?86*)
 			aros_target_cpu="i386"
@@ -8638,6 +8640,8 @@ echo "$as_me: error: \"Unknown CPU for CygWin -- $target_cpu\"" >&2;}
     mingw32*)
         aros_target_arch="mingw32"
 	aros_shared_default="no"
+	need_dlopen="no"
+	rescomp="windres"
 	case "$target_cpu" in
 	    *i?86*)
 		aros_target_cpu="i386"
@@ -8656,6 +8660,7 @@ echo "$as_me: error: \"Unknown CPU for CygWin -- $target_cpu\"" >&2;}
 		aros_target_strip="i386-aros-strip"
 		aros_target_objcopy="i386-aros-objcopy"
 		aros_target_objdump="i386-aros-objdump"
+		target_tool_prefix="i386-mingw32-"
 		;;
 	    *)
 		{ { echo "$as_me:$LINENO: error: \"Unknown CPU for Mingw32 -- $target_cpu\"" >&5
@@ -9273,7 +9278,9 @@ fi
 # Set prefix for target compiler etc. if we're cross-compiling
 # (should possibly be earlier but needs to be after AC_PROG_CC)
 if test "$cross_compiling" = "yes" ; then
-    target_tool_prefix=${target_cpu}-elf-
+    if test "$target_tool_prefix" = ""; then
+	target_tool_prefix=${target_cpu}-elf-
+    fi
     CC=${target_tool_prefix}gcc
 fi
 
@@ -10912,6 +10919,186 @@ fi
 echo "$as_me: error: strip is required to build AROS. Please install and run configure again." >&2;}
    { (exit 1); exit 1; }; }
 fi
+    if test "$rescomp" != ""; then
+
+if test "$aros_kernel_rescomp" = ""; then
+    if test "$cross_compiling" = "yes" ; then
+        # Extract the first word of "${target_tool_prefix}$rescomp", so it can be a program name with args.
+set dummy ${target_tool_prefix}$rescomp; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_aros_kernel_rescomp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $aros_kernel_rescomp in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_aros_kernel_rescomp="$aros_kernel_rescomp" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_aros_kernel_rescomp="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+aros_kernel_rescomp=$ac_cv_path_aros_kernel_rescomp
+if test -n "$aros_kernel_rescomp"; then
+  { echo "$as_me:$LINENO: result: $aros_kernel_rescomp" >&5
+echo "${ECHO_T}$aros_kernel_rescomp" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+    else
+        if test "$GCC" = "yes"; then
+    aros_gcc_$rescomp=`$CC -print-prog-name=$rescomp`
+    # Extract the first word of "`basename $aros_gcc_[$rescomp]`", so it can be a program name with args.
+set dummy `basename $aros_gcc_$rescomp`; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_aros_kernel_rescomp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $aros_kernel_rescomp in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_aros_kernel_rescomp="$aros_kernel_rescomp" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in `dirname $aros_gcc_$rescomp`
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_aros_kernel_rescomp="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+aros_kernel_rescomp=$ac_cv_path_aros_kernel_rescomp
+if test -n "$aros_kernel_rescomp"; then
+  { echo "$as_me:$LINENO: result: $aros_kernel_rescomp" >&5
+echo "${ECHO_T}$aros_kernel_rescomp" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+if test "$aros_kernel_rescomp" = ""; then
+    # Extract the first word of "$rescomp", so it can be a program name with args.
+set dummy $rescomp; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_aros_kernel_rescomp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $aros_kernel_rescomp in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_aros_kernel_rescomp="$aros_kernel_rescomp" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_aros_kernel_rescomp="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+aros_kernel_rescomp=$ac_cv_path_aros_kernel_rescomp
+if test -n "$aros_kernel_rescomp"; then
+  { echo "$as_me:$LINENO: result: $aros_kernel_rescomp" >&5
+echo "${ECHO_T}$aros_kernel_rescomp" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+    fi
+else
+    # Extract the first word of "$aros_kernel_rescomp", so it can be a program name with args.
+set dummy $aros_kernel_rescomp; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_aros_kernel_rescomp+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $aros_kernel_rescomp in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_aros_kernel_rescomp="$aros_kernel_rescomp" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_aros_kernel_rescomp="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+aros_kernel_rescomp=$ac_cv_path_aros_kernel_rescomp
+if test -n "$aros_kernel_rescomp"; then
+  { echo "$as_me:$LINENO: result: $aros_kernel_rescomp" >&5
+echo "${ECHO_T}$aros_kernel_rescomp" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+
+	if test "$aros_kernel_rescomp" = ""; then
+    { { echo "$as_me:$LINENO: error: $rescomp is required to build AROS. Please install and run configure again." >&5
+echo "$as_me: error: $rescomp is required to build AROS. Please install and run configure again." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+    fi
 fi
 
 aros_hostcfg_dir="bin/${aros_host_arch}-${aros_host_cpu}/gen/config"
@@ -10994,7 +11181,7 @@ fi
 echo $ECHO_N "checking for the target compiler's include path... $ECHO_C" >&6; }
 if test "$aros_target_cc_includes" = "" ; then
     #try to guess where the directory is
-    aros_target_cc_includes=`dirname \`${aros_kernel_cc} -print-libgcc-file-name\``/include
+    aros_target_cc_includes=`dirname \`${orig_target_cc} -print-libgcc-file-name\``/include
     if ! test -d $aros_target_cc_includes; then
         #the directory doesn't exist, we need to do some more work
         aros_target_cc_includes=${PWD}/${aros_gendir}/cc_include
@@ -11201,7 +11388,7 @@ echo "${ECHO_T}$nesting_supervisor" >&6; }
 
 if test "x-$aros_flavour" = "x-emulation" -o "x-$aros_flavour" = "x-emulcompat" ; then
 
-    if test "x-$aros_host_arch" != "x-darwin" ; then
+    if test "x-$need_dlopen" != "x-no" ; then
             { echo "$as_me:$LINENO: checking for dlopen" >&5
 echo $ECHO_N "checking for dlopen... $ECHO_C" >&6; }
 if test "${ac_cv_func_dlopen+set}" = set; then
@@ -12566,6 +12753,7 @@ echo "${ECHO_T}$dbus" >&6; }
 
 
 
+
 # Graphics Related
 
 
@@ -13479,6 +13667,7 @@ aros_target_objcopy_ln!$aros_target_objcopy_ln$ac_delim
 aros_target_objdump_ln!$aros_target_objdump_ln$ac_delim
 aros_target_ranlib_ln!$aros_target_ranlib_ln$ac_delim
 aros_target_strip_ln!$aros_target_strip_ln$ac_delim
+aros_kernel_rescomp!$aros_kernel_rescomp$ac_delim
 aros_target_nostdinc_cflags!$aros_target_nostdinc_cflags$ac_delim
 aros_target_nostartup_ldflags!$aros_target_nostartup_ldflags$ac_delim
 aros_target_nix_ldflags!$aros_target_nix_ldflags$ac_delim
@@ -13563,7 +13752,6 @@ aros_palm_debug_hack!$aros_palm_debug_hack$ac_delim
 aros_nesting_supervisor!$aros_nesting_supervisor$ac_delim
 ENABLE_DBUS!$ENABLE_DBUS$ac_delim
 DBUS_CFLAGS!$DBUS_CFLAGS$ac_delim
-DBUS_LIBFLAGS!$DBUS_LIBFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -13605,6 +13793,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+DBUS_LIBFLAGS!$DBUS_LIBFLAGS$ac_delim
 KERNEL_DBUS_KOBJ!$KERNEL_DBUS_KOBJ$ac_delim
 KERNEL_DBUS_INCLUDES!$KERNEL_DBUS_INCLUDES$ac_delim
 ENABLE_X11!$ENABLE_X11$ac_delim
@@ -13617,7 +13806,7 @@ gcc_target_cpu!$gcc_target_cpu$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
