Started converting to new archtool
git-svn-id: https://svn.aros.org/svn/aros/trunk@4705 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -40,6 +40,23 @@ else
   cd ..
 fi
 
+echo -n "Checking for Source Archive Tool... "
+if [ -x "archtools/archtool" ] ; then
+  echo "tools/archtools/archtool"
+else
+  echo "Not found!"
+  echo "Trying to generate it..."
+  cd archtools
+  make
+  if [ -x "archtool" ] ; then
+    echo "Successfully generated tool."
+  else
+    echo "Failed to generate tools/archtools/archtool !!!"
+    exit 10
+  fi
+  cd ..
+fi
+
 echo -n "Checking for MetaMake... "
 if [ -x "`which mmake`" ] ; then
   MMAKE="mmake"
