Upgraded GRUB2 to 2.00 release.
git-svn-id: https://svn.aros.org/svn/aros/trunk@45803 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/arch/all-pc/boot/grub2-aros/tests/partmap_test.in b/arch/all-pc/boot/grub2-aros/tests/partmap_test.in
--- a/arch/all-pc/boot/grub2-aros/tests/partmap_test.in
+++ b/arch/all-pc/boot/grub2-aros/tests/partmap_test.in
@@ -1,5 +1,6 @@
-#! /bin/sh -e
-#
+#! /bin/sh
+set -e
+
 # Copyright (C) 2010  Free Software Foundation, Inc.
 #
 # GRUB is free software: you can redistribute it and/or modify
@@ -15,23 +16,26 @@
 # You should have received a copy of the GNU General Public License
 # along with GRUB.  If not, see <http://www.gnu.org/licenses/>.
 
-parted=/sbin/parted
+parted=parted
 grubshell=@builddir@/grub-shell
 
+. "@builddir@/grub-core/modinfo.sh"
+
 create_disk_image () {
-    name=$1
+    name="$1"
     size=$2
-    qemu-img create ${name} ${size} >/dev/null
+    rm -f "${name}"
+    dd if=/dev/zero of="${name}" bs=512 count=1 seek=$((size * 2048 - 1)) status=noxfer > /dev/null
 }
 
 check_output () {
     outfile=$1
     shift
 
-    for disk in $@; do
-	if ! grep "($disk)" ${outfile} >/dev/null
+    for dsk in $@; do
+	if ! grep "($dsk)" "${outfile}" >/dev/null
 	then
-	    echo "($disk): disk/partiton not found"
+	    echo "($dsk): disk/partiton not found"
 	    exit 1
 	fi
     done
@@ -40,19 +44,32 @@ check_output () {
 list_parts () {
     mod=$1;
     shift;
-    imgfile=$1
+    imgfile="$1"
     shift
-    outfile=$1
+    outfile="$1"
     shift
 
-    echo ls | ${grubshell} --boot=cd --qemu-opts="-hda ${imgfile}" \
-	--modules=$mod | tr -d "\n\r" > ${outfile}
-    cat ${outfile}
+    echo ls | "${grubshell}" --qemu-opts="-hda ${imgfile}" \
+	--modules=$mod | tr -d "\n\r" > "${outfile}"
+    cat "${outfile}"
     echo
 }
 
-imgfile=`mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"` || exit 1
-outfile=`mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"` || exit 1
+case "${grub_modinfo_target_cpu}-${grub_modinfo_platform}" in
+    mips-qemu_mips | mipsel-qemu_mips | i386-qemu | i386-multiboot | i386-coreboot | mipsel-loongson)
+	disk=ata0
+	;;
+    powerpc-ieee1275)
+	disk=ieee1275//pci@80000000/mac-io@4/ata-3@20000/disk@0
+	# QEMU firmware has bugs which prevent it from accessing hard disk.
+	exit 0
+	;;
+    *)
+	disk=hd0
+	;;
+esac
+imgfile="`mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"`" || exit 1
+outfile="`mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"`" || exit 1
 
 #
 # MSDOS partition types
@@ -61,64 +78,64 @@ outfile=`mktemp "${TMPDIR:-/tmp}/tmp.XXXXXXXXXX"` || exit 1
 echo "Checking MSDOS partition types..."
 
 # 0 primary
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel msdos
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel msdos
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk
 
 # 1 primary
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M 
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M 
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1
 
 # 2 primary
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos2
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos2
 
 # 3 primary
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart primary 20M 30M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos2 hd0,msdos3
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart primary 20M 30M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos2 $disk,msdos3
 
 # 4 primary
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart primary 20M 30M mkpart primary 30M 40M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos2 hd0,msdos3 hd0,msdos4
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart primary 20M 30M mkpart primary 30M 40M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos2 $disk,msdos3 $disk,msdos4
 
 # 1 primary, 1 extended
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100%
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100%
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1
 
 # 1 primary, 1 extended, 1 logical
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos5
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos5
 
 # 1 primary, 1 extended, 2 logical
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M mkpart logical 30M 40M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos5 hd0,msdos6
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M mkpart logical 30M 40M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos5 $disk,msdos6
 
 # 1 primary, 1 extended, 3 logical
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M mkpart logical 30M 40M mkpart logical 40M 50M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos5 hd0,msdos6 hd0,msdos7
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M mkpart logical 30M 40M mkpart logical 40M 50M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos5 $disk,msdos6 $disk,msdos7
 
 # 1 primary, 1 extended, 4 logical
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M mkpart logical 30M 40M mkpart logical 40M 50M mkpart logical 50M 60M
-list_parts part_msdos ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,msdos1 hd0,msdos5 hd0,msdos6 hd0,msdos7 hd0,msdos8
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel msdos mkpart primary 0 10M mkpart primary 10M 20M mkpart extended 20M 100% mkpart logical 20M 30M mkpart logical 30M 40M mkpart logical 40M 50M mkpart logical 50M 60M
+list_parts part_msdos "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,msdos1 $disk,msdos5 $disk,msdos6 $disk,msdos7 $disk,msdos8
 
 
 #
@@ -128,46 +145,46 @@ check_output ${outfile} hd0 hd0,msdos1 hd0,msdos5 hd0,msdos6 hd0,msdos7 hd0,msdo
 echo "Checking GPT partition types..."
 
 # 0 parts
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel gpt
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel gpt
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk
 
 # 1 parts
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel gpt mkpart 1 0 10M 
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,gpt1
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel gpt mkpart 1 0 10M 
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,gpt1
 
 # 2 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,gpt1 hd0,gpt2
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,gpt1 $disk,gpt2
 
 # 3 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 3 20M 30M
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,gpt1 hd0,gpt2 hd0,gpt3
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 3 20M 30M
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,gpt1 $disk,gpt2 $disk,gpt3
 
 # 4 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 4 20M 30M mkpart 5 30M 40M
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,gpt1 hd0,gpt2 hd0,gpt3 hd0,gpt4
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 4 20M 30M mkpart 5 30M 40M
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,gpt1 $disk,gpt2 $disk,gpt3 $disk,gpt4
 
 # 5 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 3 20M 30M mkpart 4 30M 40M mkpart 5 40M 50M
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,gpt1 hd0,gpt2 hd0,gpt3 hd0,gpt4 hd0,gpt5
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 3 20M 30M mkpart 4 30M 40M mkpart 5 40M 50M
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,gpt1 $disk,gpt2 $disk,gpt3 $disk,gpt4 $disk,gpt5
 
 # 6 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 3 20M 30M mkpart 4 30M 40M mkpart 5 40M 50M mkpart 6 50M 60M
-list_parts part_gpt ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,gpt1 hd0,gpt2 hd0,gpt3 hd0,gpt4 hd0,gpt5 hd0,gpt6
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel gpt mkpart 1 0 10M mkpart 2 10M 20M mkpart 3 20M 30M mkpart 4 30M 40M mkpart 5 40M 50M mkpart 6 50M 60M
+list_parts part_gpt "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,gpt1 $disk,gpt2 $disk,gpt3 $disk,gpt4 $disk,gpt5 $disk,gpt6
 
 
 #
@@ -179,46 +196,46 @@ check_output ${outfile} hd0 hd0,gpt1 hd0,gpt2 hd0,gpt3 hd0,gpt4 hd0,gpt5 hd0,gpt
 echo "Checking SUN partition types..."
 
 # 0 parts
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel sun
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel sun
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk
 
 # 1 parts
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel sun mkpart 0 10M 
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,sun1
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel sun mkpart 0 10M 
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,sun1
 
 # 2 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel sun mkpart 0 10M mkpart 10M 20M
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,sun1 hd0,sun2
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel sun mkpart 0 10M mkpart 10M 20M
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,sun1 $disk,sun2
 
 # 3 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,sun1 hd0,sun2 hd0,sun4
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,sun1 $disk,sun2 $disk,sun4
 
 # 4 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M mkpart 30M 40M
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,sun1 hd0,sun2 hd0,sun4 hd0,sun5
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M mkpart 30M 40M
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,sun1 $disk,sun2 $disk,sun4 $disk,sun5
 
 # 5 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M mkpart 30M 40M mkpart 40M 50M
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,sun1 hd0,sun2 hd0,sun4 hd0,sun5 hd0,sun6
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M mkpart 30M 40M mkpart 40M 50M
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,sun1 $disk,sun2 $disk,sun4 $disk,sun5 $disk,sun6
 
 # 6 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M mkpart 30M 40M mkpart 40M 50M mkpart 50M 60M
-list_parts part_sun ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,sun1 hd0,sun2 hd0,sun4 hd0,sun5 hd0,sun6 hd0,sun7
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel sun mkpart 0 10M mkpart 10M 20M mkpart 20M 30M mkpart 30M 40M mkpart 40M 50M mkpart 50M 60M
+list_parts part_sun "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,sun1 $disk,sun2 $disk,sun4 $disk,sun5 $disk,sun6 $disk,sun7
 
 
 #
@@ -232,43 +249,43 @@ check_output ${outfile} hd0 hd0,sun1 hd0,sun2 hd0,sun4 hd0,sun5 hd0,sun6 hd0,sun
 echo "Checking APPLE partition types..."
 
 # 0 parts
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel mac
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel mac
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2
 
 # 1 parts
-create_disk_image ${imgfile} 64M
-${parted} -a none -s ${imgfile} mklabel mac mkpart a 1M 10M
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2 hd0,apple3
+create_disk_image "${imgfile}" 64
+${parted} -a none -s "${imgfile}" mklabel mac mkpart a 1M 10M
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2 $disk,apple3
 
 # 2 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel mac mkpart a 1M 10M mkpart b 10M 20M
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2 hd0,apple3 hd0,apple4
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel mac mkpart a 1M 10M mkpart b 10M 20M
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2 $disk,apple3 $disk,apple4
 
 # 3 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2 hd0,apple4 hd0,apple5
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2 $disk,apple4 $disk,apple5
 
 # 4 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M mkpart d 30M 40M
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2 hd0,apple4 hd0,apple5 hd0,apple6
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M mkpart d 30M 40M
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2 $disk,apple4 $disk,apple5 $disk,apple6
 
 # 5 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M mkpart d 30M 40M mkpart e 40M 50M
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2 hd0,apple4 hd0,apple5 hd0,apple6 hd0,apple7
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M mkpart d 30M 40M mkpart e 40M 50M
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2 $disk,apple4 $disk,apple5 $disk,apple6 $disk,apple7
 
 # 6 parts
-create_disk_image ${imgfile} 128M
-${parted} -a none -s ${imgfile} mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M mkpart d 30M 40M mkpart e 40M 50M mkpart f 50M 60M
-list_parts part_apple ${imgfile} ${outfile}
-check_output ${outfile} hd0 hd0,apple1 hd0,apple2 hd0,apple4 hd0,apple5 hd0,apple6 hd0,apple7 hd0,apple8
+create_disk_image "${imgfile}" 128
+${parted} -a none -s "${imgfile}" mklabel mac mkpart a 1M 10M mkpart b 10M 20M mkpart c 20M 30M mkpart d 30M 40M mkpart e 40M 50M mkpart f 50M 60M
+list_parts part_apple "${imgfile}" "${outfile}"
+check_output "${outfile}" $disk $disk,apple1 $disk,apple2 $disk,apple4 $disk,apple5 $disk,apple6 $disk,apple7 $disk,apple8
diff --git a/arch/all-pc/boot/grub2-aros/util/grub-mkconfig_lib.in b/arch/all-pc/boot/grub2-aros/util/grub-mkconfig_lib.in
--- a/arch/all-pc/boot/grub2-aros/util/grub-mkconfig_lib.in
+++ b/arch/all-pc/boot/grub2-aros/util/grub-mkconfig_lib.in
@@ -16,74 +16,94 @@
 
 transform="@program_transform_name@"
 
-prefix=@prefix@
-exec_prefix=@exec_prefix@
-datarootdir=@datarootdir@
-datadir=@datadir@
-bindir=@bindir@
-sbindir=@sbindir@
-pkgdatadir=${datadir}/`echo @PACKAGE_TARNAME@ | sed "${transform}"`
+prefix="@prefix@"
+exec_prefix="@exec_prefix@"
+datarootdir="@datarootdir@"
+datadir="@datadir@"
+bindir="@bindir@"
+sbindir="@sbindir@"
+pkgdatadir="${datadir}/@PACKAGE@"
 
 if test "x$grub_probe" = x; then
-  grub_probe=${sbindir}/`echo grub-probe | sed ${transform}`
+  grub_probe="${sbindir}/`echo grub-probe | sed "${transform}"`"
 fi
 if test "x$grub_mkrelpath" = x; then
-  grub_mkrelpath=${bindir}/`echo grub-mkrelpath | sed ${transform}`
+  grub_mkrelpath="${bindir}/`echo grub-mkrelpath | sed "${transform}"`"
 fi
 
-if $(which gettext >/dev/null 2>/dev/null) ; then
-  gettext="gettext"
+if which gettext >/dev/null 2>/dev/null; then
+  :
 else
-  gettext="echo"
+  gettext () {
+     printf "%s" "$@"
+  }
 fi
 
 grub_warn ()
 {
-  echo "Warning: $@" >&2
+  echo "$(gettext "Warning:")" "$@" >&2
 }
 
 make_system_path_relative_to_its_root ()
 {
-  ${grub_mkrelpath} $1
+  "${grub_mkrelpath}" "$1"
 }
 
 is_path_readable_by_grub ()
 {
-  path=$1
+  path="$1"
 
   # abort if path doesn't exist
-  if test -e $path ; then : ;else
+  if test -e "$path" ; then : ;else
     return 1
   fi
 
   # abort if file is in a filesystem we can't read
-  if ${grub_probe} -t fs $path > /dev/null 2>&1 ; then : ; else
+  if "${grub_probe}" -t fs "$path" > /dev/null 2>&1 ; then : ; else
     return 1
   fi
+
+  # ... or if we can't figure out the abstraction module, for example if
+  # memberlist fails on an LVM volume group.
+  if abstractions="`"${grub_probe}" -t abstraction "$path"`" 2>&1 ; then 
+      :
+  else
+    return 1
+  fi
+
+  if [ x$GRUB_CRYPTODISK_ENABLE = xy ]; then
+      return 0
+  fi
+  
+  for abstraction in $abstractions; do
+      if [ "x$abstraction" = xcryptodisk ]; then
+	  return 1
+      fi
+  done
 
   return 0
 }
 
 convert_system_path_to_grub_path ()
 {
-  path=$1
+  path="$1"
 
   grub_warn "convert_system_path_to_grub_path() is deprecated.  Use prepare_grub_to_access_device() instead."
 
   # abort if GRUB can't access the path
-  if is_path_readable_by_grub ${path} ; then : ; else
+  if is_path_readable_by_grub "${path}" ; then : ; else
     return 1
   fi
 
-  if drive=`${grub_probe} -t drive $path` ; then : ; else
+  if drive="`"${grub_probe}" -t drive "$path"`" ; then : ; else
     return 1
   fi
 
-  if relative_path=`make_system_path_relative_to_its_root $path` ; then : ; else
+  if relative_path="`make_system_path_relative_to_its_root "$path"`" ; then : ; else
     return 1
   fi
 
-  echo ${drive}${relative_path}
+  echo "${drive}${relative_path}"
 }
 
 save_default_entry ()
@@ -97,29 +117,58 @@ EOF
 
 prepare_grub_to_access_device ()
 {
-  device=$1
+  device="$1"
+
+  partmap="`"${grub_probe}" --device "${device}" --target=partmap`"
+  for module in ${partmap} ; do
+    case "${module}" in
+      netbsd | openbsd)
+        echo "insmod part_bsd";;
+      *)
+        echo "insmod part_${module}";;
+    esac
+  done
 
   # Abstraction modules aren't auto-loaded.
-  abstraction="`${grub_probe} --device ${device} --target=abstraction`"
+  abstraction="`"${grub_probe}" --device "${device}" --target=abstraction`"
   for module in ${abstraction} ; do
     echo "insmod ${module}"
   done
 
-  partmap="`${grub_probe} --device ${device} --target=partmap`"
-  for module in ${partmap} ; do
-    echo "insmod part_${module}"
-  done
-
-  fs="`${grub_probe} --device ${device} --target=fs`"
+  fs="`"${grub_probe}" --device "${device}" --target=fs`"
   for module in ${fs} ; do
     echo "insmod ${module}"
   done
 
+  if [ x$GRUB_CRYPTODISK_ENABLE = xy ]; then
+      for uuid in "`"${grub_probe}" --device "${device}" --target=cryptodisk_uuid`"; do
+	  echo "cryptomount -u $uuid"
+      done
+  fi
+
   # If there's a filesystem UUID that GRUB is capable of identifying, use it;
   # otherwise set root as per value in device.map.
-  echo "set root='`${grub_probe} --device ${device} --target=drive`'"
-  if fs_uuid="`${grub_probe} --device ${device} --target=fs_uuid 2> /dev/null`" ; then
-    echo "search --no-floppy --fs-uuid --set=root ${fs_uuid}"
+  fs_hint="`"${grub_probe}" --device "${device}" --target=compatibility_hint`"
+  if [ "x$fs_hint" != x ]; then
+    echo "set root='$fs_hint'"
+  fi
+  if fs_uuid="`"${grub_probe}" --device "${device}" --target=fs_uuid 2> /dev/null`" ; then
+    hints="`"${grub_probe}" --device "${device}" --target=hints_string 2> /dev/null`" || hints=
+    echo "if [ x\$feature_platform_search_hint = xy ]; then"
+    echo "  search --no-floppy --fs-uuid --set=root ${hints} ${fs_uuid}"
+    echo "else"
+    echo "  search --no-floppy --fs-uuid --set=root ${fs_uuid}"
+    echo "fi"
+  fi
+}
+
+grub_get_device_id ()
+{
+  device="$1"
+  if fs_uuid="`"${grub_probe}" --device "${device}" --target=fs_uuid 2> /dev/null`" ; then
+    echo "$fs_uuid";
+  else
+    echo "$device"
   fi
 }
 
@@ -128,7 +177,8 @@ grub_file_is_not_garbage ()
   if test -f "$1" ; then
     case "$1" in
       *.dpkg-*) return 1 ;; # debian dpkg
-      README*)  return 1 ;; # documentation
+      *.rpmsave|*.rpmnew) return 1 ;;
+      README*|*/README*)  return 1 ;; # documentation
     esac
   else
     return 1
@@ -136,23 +186,41 @@ grub_file_is_not_garbage ()
   return 0
 }
 
+version_sort ()
+{
+  case $version_sort_sort_has_v in
+    yes)
+      LC_ALL=C sort -V;;
+    no)
+      LC_ALL=C sort -n;;
+    *)
+      if sort -V </dev/null > /dev/null 2>&1; then
+        version_sort_sort_has_v=yes
+	LC_ALL=C sort -V
+      else
+        version_sort_sort_has_v=no
+        LC_ALL=C sort -n
+      fi;;
+   esac
+}
+
 version_test_numeric ()
 {
-  local a=$1
-  local cmp=$2
-  local b=$3
-  if [ "$a" = "$b" ] ; then
-    case $cmp in
+  version_test_numeric_a="$1"
+  version_test_numeric_cmp="$2"
+  version_test_numeric_b="$3"
+  if [ "$version_test_numeric_a" = "$version_test_numeric_b" ] ; then
+    case "$version_test_numeric_cmp" in
       ge|eq|le) return 0 ;;
       gt|lt) return 1 ;;
     esac
   fi
-  if [ "$cmp" = "lt" ] ; then
-    c=$a
-    a=$b
-    b=$c
+  if [ "$version_test_numeric_cmp" = "lt" ] ; then
+    version_test_numeric_c="$version_test_numeric_a"
+    version_test_numeric_a="$version_test_numeric_b"
+    version_test_numeric_b="$version_test_numeric_c"
   fi
-  if (echo $a ; echo $b) | sort -n | head -n 1 | grep -qx $b ; then
+  if (echo "$version_test_numeric_a" ; echo "$version_test_numeric_b") | version_sort | head -n 1 | grep -qx "$version_test_numeric_b" ; then
     return 0
   else
     return 1
@@ -161,56 +229,123 @@ version_test_numeric ()
 
 version_test_gt ()
 {
-  local a=`echo $1 | sed -e "s/[^-]*-//"`
-  local b=`echo $2 | sed -e "s/[^-]*-//"`
-  local cmp=gt
-  if [ "x$b" = "x" ] ; then
+  version_test_gt_a="`echo "$1" | sed -e "s/[^-]*-//"`"
+  version_test_gt_b="`echo "$2" | sed -e "s/[^-]*-//"`"
+  version_test_gt_cmp=gt
+  if [ "x$version_test_gt_b" = "x" ] ; then
     return 0
   fi
-  case $a:$b in
+  case "$version_test_gt_a:$version_test_gt_b" in
     *.old:*.old) ;;
-    *.old:*) a=`echo -n $a | sed -e s/\.old$//` ; cmp=gt ;;
-    *:*.old) b=`echo -n $b | sed -e s/\.old$//` ; cmp=ge ;;
+    *.old:*) version_test_gt_a="`echo -n "$version_test_gt_a" | sed -e 's/\.old$//'`" ; version_test_gt_cmp=gt ;;
+    *:*.old) version_test_gt_b="`echo -n "$version_test_gt_b" | sed -e 's/\.old$//'`" ; version_test_gt_cmp=ge ;;
   esac
-  version_test_numeric $a $cmp $b
-  return $?
+  version_test_numeric "$version_test_gt_a" "$version_test_gt_cmp" "$version_test_gt_b"
+  return "$?"
 }
 
 version_find_latest ()
 {
-  local a=""
-  for i in $@ ; do
-    if version_test_gt "$i" "$a" ; then
-      a="$i"
+  version_find_latest_a=""
+  for i in "$@" ; do
+    if version_test_gt "$i" "$version_find_latest_a" ; then
+      version_find_latest_a="$i"
     fi
   done
-  echo "$a"
+  echo "$version_find_latest_a"
 }
 
 # One layer of quotation is eaten by "", the second by sed, and the third by
 # printf; so this turns ' into \'.  Note that you must use the output of
 # this function in a printf format string.
+
+grub_quote () {
+  sed "s/'/'\\\\\\\\''/g"
+}
+
 gettext_quoted () {
-  $gettext "$@" | sed "s/'/'\\\\\\\\''/g"
+  gettext "$@" | sed "s/'/'\\\\\\\\''/g"
 }
 
 # Run the first argument through gettext_quoted, and then pass that and all
 # remaining arguments to printf.  This is a useful abbreviation and tends to
 # be easier to type.
 gettext_printf () {
-  local format="$1"
+  gettext_printf_format="$1"
   shift
-  printf "$(gettext_quoted "$format")" "$@"
+  printf "$(gettext "$gettext_printf_format")" "$@"
 }
 
 uses_abstraction () {
-  device=$1
+  device="$1"
 
-  abstraction="`${grub_probe} --device ${device} --target=abstraction`"
+  abstraction="`"${grub_probe}" --device "${device}" --target=abstraction`"
   for module in ${abstraction}; do
     if test "x${module}" = "x$2"; then
       return 0
     fi
   done
   return 1
+}
+
+print_option_help () {
+  if test x$print_option_help_wc = x; then
+      if wc -L  </dev/null > /dev/null 2>&1; then
+	  print_option_help_wc=-L
+      elif wc -m  </dev/null > /dev/null 2>&1; then
+	  print_option_help_wc=-m
+      else
+	  print_option_help_wc=-b
+      fi
+  fi
+  if test x$grub_have_fmt = x; then
+      if fmt -w 40  </dev/null > /dev/null 2>&1; then
+	  grub_have_fmt=y;
+      else
+	  grub_have_fmt=n;
+      fi
+  fi
+  print_option_help_lead="  $1"
+  print_option_help_lspace="$(echo "$print_option_help_lead" | wc $print_option_help_wc)"
+  print_option_help_fill="$((26 - print_option_help_lspace))"
+  printf "%s" "$print_option_help_lead"
+  if test $print_option_help_fill -le 0; then
+      print_option_help_nl=y
+      echo
+  else
+      print_option_help_i=0;
+      while test $print_option_help_i -lt $print_option_help_fill; do
+      printf " "
+	  print_option_help_i=$((print_option_help_i+1))
+      done
+      print_option_help_nl=n
+  fi
+  if test x$grub_have_fmt = xy; then
+      print_option_help_split="$(echo "$2" | fmt -w 50)"
+  else
+      print_option_help_split="$2"
+  fi
+  if test x$print_option_help_nl = xy; then
+      echo "$print_option_help_split" | awk \
+	  '{ print "                          " $0; }'
+  else
+      echo "$print_option_help_split" | awk 'BEGIN   { n = 0 }
+  { if (n == 1) print "                          " $0; else print $0; n = 1 ; }'
+  fi
+}
+
+grub_fmt () {
+  if test x$grub_have_fmt = x; then
+      if fmt -w 40 < /dev/null > /dev/null; then
+	  grub_have_fmt=y;
+      else
+	  grub_have_fmt=n;
+      fi
+  fi
+
+  if test x$grub_have_fmt = xy; then
+      fmt
+  else
+      cat
+  fi
 }
