First part of updating GRUB to 0.93. I hope I didn't get anything wrong. There are still 3 files to update in stage2/, namely builtins.c, common.c and boot.c. The build might break before those are commited, but I plan to let Johan Grip do those files. ;-)
git-svn-id: https://svn.aros.org/svn/aros/trunk@16681 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/arch/i386-pc/boot/grub/util/grub-install.in b/arch/i386-pc/boot/grub/util/grub-install.in
--- a/arch/i386-pc/boot/grub/util/grub-install.in
+++ b/arch/i386-pc/boot/grub/util/grub-install.in
@@ -1,7 +1,7 @@
 #! /bin/sh
 
 # Install GRUB on your drive.
-#   Copyright (C) 1999, 2000 Free Software Foundation, Inc.
+#   Copyright (C) 1999,2000,2001,2002 Free Software Foundation, Inc.
 #
 # This file is free software; you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by
@@ -31,6 +31,7 @@ pkgdatadir=${datadir}/${PACKAGE}/${host_cpu}-${host_vendor}
 
 grub_shell=${sbindir}/grub
 log_file=/tmp/grub-install.log.$$
+img_file=/tmp/grub-install.img.$$
 rootdir=
 grub_prefix=/boot/grub
 
@@ -38,6 +39,18 @@ install_device=
 force_lba=
 recheck=no
 debug=no
+
+# look for secure tempfile creation wrappers on this platform
+if test -x /bin/tempfile; then
+    mklog="/bin/tempfile --prefix=grub"
+    mkimg="/bin/tempfile --prefix=grub"
+elif test -x /bin/mktemp; then
+    mklog="/bin/mktemp /tmp/grub-install.log.XXXXXX"
+    mkimg="/bin/mktemp /tmp/grub-install.img.XXXXXX"
+else
+    mklog=""
+    mkimg=""
+fi
 
 # Usage: usage
 # Print the usage.
@@ -96,6 +109,12 @@ convert () {
 	    | sed "s%.*/r\{0,1\}[saw]d[0-9]\(s[0-9]*[a-h]\)%\1%" \
        	    | sed "s%.*/r\{0,1\}da[0-9]\(s[0-9]*[a-h]\)%\1%"`
 	;;
+    netbsd*)
+	tmp_disk=`echo "$1" | sed 's%r\{0,1\}\([sw]d[0-9]*\).*$%r\1d%' \
+	    | sed 's%r\{0,1\}\(fd[0-9]*\).*$%r\1a%'`
+	tmp_part=`echo "$1" \
+	    | sed "s%.*/r\{0,1\}[sw]d[0-9]\([abe-p]\)%\1%"`
+	;;
     *)
 	echo "grub-install does not support your OS yet." 1>&2
 	exit 1 ;;
@@ -145,11 +164,48 @@ convert () {
 		    | sed "s%)%,$tmp_bsd_partition)%"`
 	    fi
 	    echo "$tmp_drive" ;;
+	netbsd*)
+	    if echo $tmp_part | grep "^[abe-p]$" >/dev/null; then
+		tmp_bsd_partition=`echo "$tmp_part" \
+		    | sed "s%\([a-p]\)$%\1%"`
+		tmp_drive=`echo "$tmp_drive" \
+		    | sed "s%)%,$tmp_bsd_partition)%"`
+	    fi
+	    echo "$tmp_drive" ;;
 	esac
     else
 	# If no partition is specified, just print the drive name.
 	echo "$tmp_drive"
     fi
+}
+
+# Usage: find_device file
+# Find block device on which the file resides.
+find_device () {
+    # For now, this uses the program `df' to get the device name, but is
+    # this really portable?
+    tmp_fname=`df $1/ | sed -n 's%.*\(/dev/[^ 	]*\).*%\1%p'`
+
+    if test -z "$tmp_fname"; then
+	echo "Could not find device for $1" 2>&1
+	exit 1
+    fi
+
+    # Resolve symlinks
+    while test -L $tmp_fname; do
+	tmp_new_fname=`ls -al $tmp_fname | sed -n 's%.*-> %\1%p'`
+	if test -z "$tmp_new_fname"; then
+	    echo "Unrecognized ls output" 2>&1
+	    exit 1
+	fi
+
+	# Convert relative symlinks
+	case $tmp_new_fname in
+	    /*) tmp_fname="$tmp_new_fname" ;;
+	    *) tmp_fname="`echo $tmp_fname | sed 's%/[^/]*$%%'`/$tmp_new_fname" ;;
+	esac
+    done
+    echo "$tmp_fname"
 }
 
 # Check the arguments.
@@ -199,7 +255,19 @@ if test $debug = yes; then
 fi
 
 # Initialize these directories here, since ROOTDIR was initialized.
-bootdir=${rootdir}/boot
+case "$host_os" in
+netbsd*)
+    # Because /boot is used for the boot block in NetBSD, use /grub
+    # instead of /boot/grub.
+    grub_prefix=/grub
+    bootdir=${rootdir}
+    ;;
+*)
+    # Use /boot/grub by default.
+    bootdir=${rootdir}/boot
+    ;;
+esac
+
 grubdir=${bootdir}/grub
 device_map=${grubdir}/device.map
 
@@ -242,7 +310,7 @@ if test -f "$device_map"; then
     :
 else
     # Create a safe temporary file.
-    test -x /bin/tempfile && log_file=`tempfile --prefix=grub`
+    test -n "$mklog" && log_file=`$mklog`
 
     $grub_shell --batch --device-map=$device_map <<EOF >$log_file
 quit
@@ -253,6 +321,14 @@ EOF
     fi
 
     rm -f $log_file
+fi
+
+# Make sure that there is no duplicated entry.
+tmp=`sed -n '/^([fh]d[0-9]*)/s/\(^(.*)\).*/\1/p' $device_map \
+    | sort | uniq -d | sed -n 1p`
+if test -n "$tmp"; then
+    echo "The drive $tmp is defined multiple times in the device map $device_map" 1>&2
+    exit 1
 fi
 
 # Check for INSTALL_DEVICE.
@@ -273,12 +349,8 @@ case "$install_device" in
 esac
 
 # Get the root drive.
-# For now, this uses the program `df' to get the device name, but is
-# this really portable?
-root_device=`df ${rootdir}/ | grep /dev/ \
-    | sed 's%.*\(/dev/[^ 	]*\).*%\1%'`
-bootdir_device=`df ${bootdir} | grep /dev/ \
-    | sed 's%.*\(/dev/[^ 	]*\).*%\1%'`
+root_device=`find_device ${rootdir}`
+bootdir_device=`find_device ${bootdir}`
 
 # Check if the boot directory is in the same device as the root directory.
 if test "x$root_device" != "x$bootdir_device"; then
@@ -295,8 +367,8 @@ fi
 
 # Check if the root directory exists in the same device as the grub
 # directory.
-grubdir_device=`df ${grubdir} | grep /dev/ \
-    | sed 's%.*\(/dev/[^ 	]*\).*%\1%'`
+grubdir_device=`find_device ${grubdir}`
+
 if test "x$grubdir_device" != "x$root_device"; then
     # For now, cannot deal with this situation.
     cat <<EOF 1>&2
@@ -315,8 +387,37 @@ for file in \
     cp -f $file ${grubdir} || exit 1
 done
 
+# Make sure that GRUB reads the same images as the host OS.
+test -n "$mkimg" && img_file=`$mkimg`
+test -n "$mklog" && log_file=`$mklog`
+
+for file in ${grubdir}/stage1 ${grubdir}/stage2 ${grubdir}/*stage1_5; do
+    count=5
+    tmp=`echo $file | sed "s|^${grubdir}|${grub_prefix}|"`
+    while test $count -gt 0; do
+	$grub_shell --batch --device-map=$device_map <<EOF >$log_file
+dump ${root_drive}${tmp} ${img_file}
+quit
+EOF
+	if grep "Error [0-9]*: " $log_file >/dev/null; then
+	    :
+	elif cmp $file $img_file >/dev/null; then
+	    break
+	fi
+	sleep 1
+	count=`expr $count - 1`    
+    done
+    if test $count -eq 0; then
+	echo "The file $file not read correctly." 1>&2
+	exit 1
+    fi
+done
+
+rm -f $img_file
+rm -f $log_file
+
 # Create a safe temporary file.
-test -x /bin/tempfile && log_file=`tempfile --prefix=grub`
+test -n "$mklog" && log_file=`$mklog`
 
 # Now perform the installation.
 $grub_shell --batch --device-map=$device_map <<EOF >$log_file
