Merged sfdc 1.3.
git-svn-id: https://svn.aros.org/svn/aros/trunk@22555 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/tools/sfdc/configure b/tools/sfdc/configure
--- a/tools/sfdc/configure
+++ b/tools/sfdc/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52 for sfdc 1.1.
+# Generated by Autoconf 2.52 for sfdc 1.3.
 #
 # Report bugs to <martin@blom.org>.
 #
@@ -151,8 +151,8 @@ mandir='${prefix}/man'
 # Identity of this package.
 PACKAGE_NAME='sfdc'
 PACKAGE_TARNAME='sfdc'
-PACKAGE_VERSION='1.1'
-PACKAGE_STRING='sfdc 1.1'
+PACKAGE_VERSION='1.3'
+PACKAGE_STRING='sfdc 1.3'
 PACKAGE_BUGREPORT='martin@blom.org'
 
 ac_prev=
@@ -566,7 +566,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<EOF
-\`configure' configures sfdc 1.1 to adapt to many kinds of systems.
+\`configure' configures sfdc 1.3 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -627,7 +627,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of sfdc 1.1:";;
+     short | recursive ) echo "Configuration of sfdc 1.3:";;
    esac
   cat <<\EOF
 
@@ -674,7 +674,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\EOF
-sfdc configure 1.1
+sfdc configure 1.3
 generated by GNU Autoconf 2.52
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -689,7 +689,7 @@ cat >&5 <<EOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by sfdc $as_me 1.1, which was
+It was created by sfdc $as_me 1.3, which was
 generated by GNU Autoconf 2.52.  Invocation command line was
 
   $ $0 $@
@@ -916,8 +916,8 @@ fi
 PATH_SEPARATOR="$ac_path_separator"
 rm -f conftest.sh
 
-VERSION=1.1
-DATE=2003-12-22
+VERSION=1.3
+DATE=2004-11-12
 
 # Checks for programs.
 for ac_prog in perl
@@ -1145,7 +1145,7 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 # Checks for library functions.
 
-ac_config_files="$ac_config_files Makefile gg-sfdc.spec"
+ac_config_files="$ac_config_files Makefile gg-sfdc.spec sfdc.readme"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1379,7 +1379,7 @@ EOF
 
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
-sfdc config.status 1.1
+sfdc config.status 1.3
 configured by $0, generated by GNU Autoconf 2.52,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
@@ -1462,7 +1462,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me (sfdc 1.1) 2.52, executed with
+This file was extended by $as_me (sfdc 1.3) 2.52, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -1480,7 +1480,8 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "gg-sfdc.spec" ) CONFIG_FILES="$CONFIG_FILES gg-sfdc.spec" ;;
-  *) { { echo "$as_me:1483: error: invalid argument: $ac_config_target" >&5
+  "sfdc.readme" ) CONFIG_FILES="$CONFIG_FILES sfdc.readme" ;;
+  *) { { echo "$as_me:1484: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1686,7 +1687,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1689: creating $ac_file" >&5
+    { echo "$as_me:1690: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1704,7 +1705,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1707: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1708: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1717,7 +1718,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1720: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1721: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
