Changes allowing to build AROS outside source tree. See "Building AROS outside source tree" thread on AROS-Dev for more details.
git-svn-id: https://svn.aros.org/svn/aros/trunk@30756 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/config/make.tmpl b/config/make.tmpl
--- a/config/make.tmpl
+++ b/config/make.tmpl
@@ -14,15 +14,15 @@
 # and use the options in %(opt).
 %define compile_q cmd=$(TARGET_CC) opt=$(CFLAGS) from=$< to=$@
 	@$(ECHO) "Compiling %(from)"
-	@$(IF) %(cmd) %(opt) -c %(from) -o %(to) > $(GENDIR)/cerrors 2>&1 ; then \
+	@$(IF) %(cmd) -iquote $(SRCDIR)/$(CURDIR) -iquote . %(opt) -c %(from) -o %(to) > $(GENDIR)/cerrors 2>&1 ; then \
 	    $(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
-		$(ECHO) "%(from): %(cmd) %(opt) -c %(from) -o %(to)" >> $(GENDIR)/errors ; \
+		$(ECHO) "%(from): %(cmd) %(opt) -iquote $(SRCDIR)/$(CURDIR) -iquote . -c %(from) -o %(to)" >> $(GENDIR)/errors ; \
 		tee < $(GENDIR)/cerrors -a $(GENDIR)/errors ; \
 	    else \
 		$(NOP) ; \
 	    fi ; \
 	else \
-	    $(ECHO) "Compile failed: %(cmd) %(opt) -c %(from) -o %(to)" 1>&2 ; \
+	    $(ECHO) "Compile failed: %(cmd) %(opt) -iquote $(SRCDIR)/$(CURDIR) -iquote . -c %(from) -o %(to)" 1>&2 ; \
 	    tee < $(GENDIR)/cerrors -a $(GENDIR)/errors 1>&2 ; \
 	    exit 1 ; \
 	fi
@@ -104,7 +104,7 @@
 %define mkdepend_q flags=$(CFLAGS) from=$< to=$@ cc=$(AROS_CC)
 	%mkdir_q dir="$(dir %(to))"
 	@$(ECHO) "Makedepend $(CURDIR)/$(notdir %(from))..."
-	@AROS_CC="%(cc)" $(MKDEPEND) %(flags) %(from) -o %(to)
+	@AROS_CC="%(cc)" $(MKDEPEND) %(flags) -I$(SRCDIR)/$(CURDIR) %(from) -o %(to)
 %end
 #------------------------------------------------------------------------------
 
@@ -354,7 +354,7 @@ TMP_WILDCARD := %(targetdir)/%
 $(TMP_TARGETS) $(TMP_DTARGETS) : | $(addsuffix .c,%(basenames))
 
 # Be sure that all .c files are found
-TMP_DIRS := $(filter-out ./,$(sort $(dir %(basenames))))
+TMP_DIRS := $(filter-out ./,$(sort $(dir %(basenames)) $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir %(basenames)))))
 ifneq ($(TMP_DIRS),)
     vpath %.c $(TMP_DIRS)
 endif
@@ -490,7 +490,7 @@ TMP_WILDCARD := %(targetdir)/%
 $(TMP_TARGETS) : | $(addsuffix %(suffix),%(basenames))
 
 # Be sure that all .c files are found
-TMP_DIRS := $(filter-out ./,$(sort $(dir %(basenames))))
+TMP_DIRS := $(filter-out ./,$(sort $(dir %(basenames)) $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir %(basenames)))))
 ifneq ($(TMP_DIRS),)
     vpath %%(suffix) $(TMP_DIRS)
 endif
@@ -704,7 +704,7 @@ TMP_WILDCARD := %(targetdir)/%.ref
 $(TMP_TARGETS) : | $(addsuffix .c,%(basenames))
 
 # Be sure that all .c files are found
-TMP_DIRS := $(filter-out ./,$(sort $(dir %(basenames))))
+TMP_DIRS := $(filter-out ./,$(sort $(dir %(basenames)) $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir %(basenames)))))
 ifneq ($(TMP_DIRS),)
     vpath %.c $(TMP_DIRS)
 endif
@@ -745,10 +745,11 @@ TMP_TARGET := %(modname)_libdefs.h
 TMP_DEPS := $(GENMODULE)
 TMP_OPTS := 
 ifneq (%(conffile),)
-    TMP_OPTS += -c %(conffile)
-    TMP_DEPS += %(conffile)
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(conffile)
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(conffile)
 else
-    TMP_DEPS += %(modname).conf
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(modname).conf
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(modname).conf
 endif
 ifneq (%(modsuffix),)
     TMP_OPTS += -s %(modsuffix)
@@ -782,10 +783,11 @@ endif
 TMP_OPTS := -r %(reffile)
 TMP_DEPS += %(reffile)
 ifneq (%(conffile),)
-    TMP_OPTS += -c %(conffile)
-    TMP_DEPS += %(conffile)
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(conffile)
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(conffile)
 else
-    TMP_DEPS += %(modname).conf
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(modname).conf
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(modname).conf
 endif
 ifneq (%(modsuffix),)
     TMP_OPTS += -s %(modsuffix)
@@ -815,10 +817,11 @@ TMP_TARGET := Makefile.%(modname)
 TMP_DEPS := $(GENMODULE)
 TMP_OPTS := 
 ifneq (%(conffile),)
-    TMP_OPTS += -c %(conffile)
-    TMP_DEPS += %(conffile)
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(conffile)
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(conffile)
 else
-    TMP_DEPS += %(modname).conf
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(modname).conf
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(modname).conf
 endif
 ifneq (%(modsuffix),)
     TMP_OPTS += -s %(modsuffix)
@@ -848,10 +851,11 @@ TMP_TARGETS := $(%(modname)_INCLUDES)
 TMP_DEPS := $(GENMODULE)
 TMP_OPTS := 
 ifneq (%(conffile),)
-    TMP_OPTS += -c %(conffile)
-    TMP_DEPS += %(conffile)
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(conffile)
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(conffile)
 else
-    TMP_DEPS += %(modname).conf
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(modname).conf
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(modname).conf
 endif
 ifneq (%(modsuffix),)
     TMP_OPTS += -s %(modsuffix)
@@ -894,10 +898,11 @@ else
     TMP_OPTS :=
 endif
 ifneq (%(conffile),)
-    TMP_OPTS += -c %(conffile)
-    TMP_DEPS += %(conffile)
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(conffile)
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(conffile)
 else
-    TMP_DEPS += %(modname).conf
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(modname).conf
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(modname).conf
 endif
 ifneq (%(modsuffix),)
     TMP_OPTS += -s %(modsuffix)
@@ -945,10 +950,11 @@ else
     TMP_OPTS :=
 endif
 ifneq (%(conffile),)
-    TMP_OPTS += -c %(conffile)
-    TMP_DEPS += %(conffile)
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(conffile)
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(conffile)
 else
-    TMP_DEPS += %(modname).conf
+    TMP_OPTS += -c $(SRCDIR)/$(CURDIR)/%(modname).conf
+    TMP_DEPS += $(SRCDIR)/$(CURDIR)/%(modname).conf
 endif
 ifneq (%(modsuffix),)
     TMP_OPTS += -s %(modsuffix)
@@ -1115,7 +1121,7 @@ GLOB_MKDIRS += $(BD_TARGETDIR) $(BD_OBJDIR)
 # assumed that all needed boiler plate code is in the files. This should only
 # be used for compiling external code. For AROS code use %build_module
 %define build_module_simple mmake=/A modname=/A modtype=/A \
-    files="$(basename $(wildcard *.c))" \
+    files="$(basename $(call WILDCARD, *.c))" \
     cflags=$(CFLAGS) dflags=$(BD_DEFDFLAGS) \
     objdir=$(OBJDIR) moduledir= \
     uselibs= usehostlibs= compiler=target
@@ -1233,7 +1239,7 @@ GLOB_MKDIRS += %(objdir) $(BD_MODDIR) $(KOBJSDIR)
 # Build a module
 # Explanation of this macro is done in the developer's manual
 %define build_module mmake=/A modname=/A modtype=/A modsuffix= \
-  conffile= files="$(basename $(wildcard *.c))" \
+  conffile= files="$(basename $(call WILDCARD, *.c))" \
   linklibfiles= linklibobjs= cflags=$(CFLAGS) dflags=$(BD_DEFDFLAGS) \
   objdir=$(OBJDIR) moduledir=$(BD_DEFMODDIR) prefix=$(AROSDIR) \
   reffile=$(BD_DEFREFFILE) noref= \
@@ -1529,7 +1535,7 @@ endif # $(TARGET) in $(BD_ALLTARGETS)
 # - objdir is where the .o are generated
 # - libdir is the directory where the linklib will be placed (default $(LIBDIR))
 %define build_linklib mmake=/A libname=/A \
-  files="$(basename $(wildcard *.c))" asmfiles=  objs= \
+  files="$(basename $(call WILDCARD, *.c))" asmfiles=  objs= \
   cflags=$(CFLAGS) dflags= aflags=$(AFLAGS) objdir=$(OBJDIR) libdir=$(LIBDIR)
 
 # assign and generate the local variables used in this macro
@@ -1568,7 +1574,7 @@ BD_LINKLIB    := %(libdir)/lib%(libname).a
 
 ifeq ($(TARGET),%(mmake))
 ifneq ($(dir $(BD_FILES)),./)
-vpath %.c $(filter-out ./,$(dir $(BD_FILES)))
+vpath %.c $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir $(BD_FILES)))
 endif
 
 %rule_compile basename=% targetdir=%(objdir) \
@@ -1601,8 +1607,8 @@ GLOB_MKDIRS += %(objdir) %(libdir)
 # - sourcedescription is the path to the FlexCat's source description file, without the .sd suffix
 
 %define build_catalogs mmake=/A name=/A subdir=/A \
- catalogs="$(basename $(wildcard *.ct))" source="../strings.h" \
- description="$(basename $(wildcard *.cd))" dir=$(AROS_CATALOGS) \
+ catalogs="$(basename $(call WILDCARD, *.ct))" source="../strings.h" \
+ description="$(basename $(call WILDCARD, *.cd))" dir=$(AROS_CATALOGS) \
  sourcedescription="$(TOOLDIR)/C_h_orig"
 
 BD_SRCS := $(addsuffix .ct, %(catalogs))
@@ -1617,12 +1623,12 @@ GLOB_MKDIRS += $(BD_DIRS)
 
 %(dir)/%/%(subdir)/%(name).catalog : %.ct %(description).cd
 	@$(ECHO) "Creating %(name) catalog for language $*."
-	@$(FLEXCAT) %(description).cd $*.ct CATALOG=%(dir)/$*/%(subdir)/%(name).catalog || [ $$? -lt 10 ]
+	@$(FLEXCAT) $(SRCDIR)/$(CURDIR)/%(description).cd $< CATALOG=%(dir)/$*/%(subdir)/%(name).catalog || [ $$? -lt 10 ]
 
 ifneq (%(source),)
 %(source) : %(description).cd
 	@$(ECHO) "Creating %(name) catalog source file %(source)"
-	@$(FLEXCAT) %(description).cd %(source)=%(sourcedescription).sd
+	@$(FLEXCAT) $(SRCDIR)/$(CURDIR)/%(description).cd %(source)=%(sourcedescription).sd
 endif
 
 %(mmake)-clean : FILES := $(BD_OJS) %(source)
@@ -1709,9 +1715,9 @@ BD_OBJS$(BDID)    := $(BD_COBJS$(BDID)) $(BD_ASMOBJS$(BDID))
 BD_DEPS$(BDID)    := $(addsuffix .d,$(addprefix $(BD_OBJDIR$(BDID))/,$(notdir %(files))))
 
 ifeq ($(TARGET),%(mainmmake)-%(arch))
-vpath %.c $(filter-out ./,$(dir %(files)))
-vpath %.s $(filter-out ./,$(dir %(asmfiles)))
-vpath %.S $(filter-out ./,$(dir %(asmfiles)))
+vpath %.c $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir %(files)))
+vpath %.s $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir %(asmfiles)))
+vpath %.S $(addprefix $(SRCDIR)/$(CURDIR)/,$(dir %(asmfiles)))
 endif
 
 $(BD_OBJS$(BDID)) : | $(BD_OBJDIR$(BDID))
@@ -1825,7 +1831,7 @@ endif
 %define copy_files_q files=$(FILES) src=. dst=/A maketarget=files-copy
 
 %(maketarget) : setup 
-	$(foreach file, %(files), $(shell $(CP) $(addprefix %(src)/, $(file)) $(addprefix %(dst)/, $(file))))
+	$(foreach file, %(files), $(shell $(CP) $(addprefix $(if $(filter /%,%(src)),%(src),$(SRCDIR)/$(CURDIR)/%(src))/, $(file)) $(addprefix %(dst)/, $(file))))
 
 setup ::
 	%mkdirs_q %(dst)
@@ -1839,9 +1845,9 @@ setup ::
 # src: the source directory whose content will be copied
 # dst: the directory where to copy src's content. If not existing, it will be made.
 
-%define copy_dir_recursive mmake=/A src=$(TOP)/$(CURDIR) dst=/A
+%define copy_dir_recursive mmake=/A src=. dst=/A
 
-%(mmake)_FILES := $(shell cd %(src); find . -path '*/CVS' -prune -o -path '*/.svn' -prune -o -name .cvsignore -prune -o -name mmakefile -prune -o -name mmakefile.src -prune -o -type f -print)
+%(mmake)_FILES := $(shell cd $(if $(filter /%,%(src)),%(src),$(SRCDIR)/$(CURDIR)/%(src)); find . -path '*/CVS' -prune -o -path '*/.svn' -prune -o -name .cvsignore -prune -o -name mmakefile -prune -o -name mmakefile.src -prune -o -type f -print)
 %(mmake)_DIRS  := $(sort $(dir $(%(mmake)_FILES)))
 
 define %(mmake)_mkdir
@@ -1869,7 +1875,7 @@ endef
 	    $(ECHO) "\$$(DST)/$$f: \$$(SRC)/$$f | \$$(dir \$$(DST)/$$f); $(CP) \$$< \$$@" >> $$m; \
 	done;  \
 	for dst in %(dst); do \
-	    $(MAKE) -f $$m DST=$$dst SRC=%(src) all; \
+	    $(MAKE) -f $$m DST=$$dst SRC=$(if $(filter /%,%(src)),%(src),$(SRCDIR)/$(CURDIR)/%(src)) all; \
 	done
 
 $(GENDIR)/$(CURDIR):
@@ -1893,10 +1899,10 @@ endif
 
 ifneq (%(dir),)
 BD_INCL_FILES := $(subst %(dir),$(GENINCDIR)/%(path),%(includes))
-BD_INC_PATH := %(dir)/
+BD_INC_PATH := $(SRCDIR)/$(CURDIR)/%(dir)/
 else
 BD_INCL_FILES := $(addprefix $(GENINCDIR)/%(path)/,%(includes))
-BD_INC_PATH :=
+BD_INC_PATH := $(SRCDIR)/$(CURDIR)/
 endif
 
 $(BD_INCL_FILES) : $(GENINCDIR)/%(path)/% : $(BD_INC_PATH)%
@@ -1928,7 +1934,7 @@ GLOB_MKDIRS += $(dir $(BD_INCL_FILES))
 
 
 %define make_hidd_stubs hidd=/A cflags=$(CFLAGS) dflags=$(CFLAGS) parenttarget=linklibs
-STUBS_SRC := $(addsuffix .c,$(STUBS))
+STUBS_SRC := $(addprefix $(SRCDIR)/$(CURDIR)/,$(addsuffix .c,$(STUBS)))
 STUBS_MEM := $(addsuffix .o,$(STUBS))
 STUBS_OBJ := $(addprefix $(OBJDIR)/,$(STUBS_MEM))
 STUBS_DEP := $(addprefix $(OBJDIR)/,$(addsuffix .d,$(STUBS)))
@@ -1980,7 +1986,7 @@ DEPS := $(DEPS) $(STUBS_DEP)
 # to the name which has to follow it.
 
 
-%define build_with_configure mmake=/A package= srcdir=$(TOP)/$(CURDIR) prefix= \
+%define build_with_configure mmake=/A package= srcdir=$(SRCDIR)/$(CURDIR) prefix= \
     aros_prefix= extraoptions= nix_dir_layout= nix=no compiler=target \
     install_target=install postconfigure= postinstall= \
     install_env=
@@ -2201,7 +2207,7 @@ endif
 #                         
 #                         The patch_subdir and patch_opt fields are optional.
 
-%define fetch archive_origins=. archive=/A suffixes= location=%destination destination=. patches_origins=. patches_specs=::
+%define fetch archive_origins=. archive=/A suffixes= location=%destination destination=. patches_origins=$(SRCDIR)/$(CURDIR) patches_specs=::
 	$(FETCH) -ao "%(archive_origins)" -a %(archive) -s "%(suffixes)" -l %(location) -d %(destination) \
         -po "%(patches_origins)" -p %(patches_specs)
 %end
@@ -2293,7 +2299,7 @@ endif
 	%fetch archive=$(%(mmake)-%(subpackage)-archbase) suffixes="%(suffixes)" \
 	    location=$(PORTSSOURCEDIR) destination=$(%(mmake)-portdir) \
 	    archive_origins=". %(package_repo)" \
-	    patches_specs="$(%(mmake)-%(subpackage)-patches_specs)" patches_origins=". %(patch_repo)"
+	    patches_specs="$(%(mmake)-%(subpackage)-patches_specs)" patches_origins="$(SRCDIR)/$(CURDIR) %(patch_repo)"
 
 #MM- %(mmake) : %(mmake)-%(subpackage)
 
