adjust linkage of c++ and arch specific support files, so it is done at the right place.

diff --git a/config/make.tmpl b/config/make.tmpl
--- a/config/make.tmpl
+++ b/config/make.tmpl
@@ -85,20 +85,20 @@ endif
 
 #------------------------------------------------------------------------------
 # Link a specified number of objects to an executable
-%define link_q cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" ldopts="$(strip $(TARGET_ISA_LDFLAGS))" ldflags="$(strip $(LDFLAGS))" from="$<" to="$@" libs="$(LIBS)" strip="$(STRIP)" stripdebug="$(DEBUG)" objdir="$(GENDIR)/$(CURDIR)" coverageinstr=
+%define link_q cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" ldopts="$(strip $(TARGET_ISA_LDFLAGS))" ldflags="$(strip $(LDFLAGS))" from="$<" to="$@" libs="$(LIBS)" archlibs= strip="$(STRIP)" stripdebug="$(DEBUG)" objdir="$(GENDIR)/$(CURDIR)" coverageinstr=
 	$(Q)$(eval LINKTARGET=%(to))
 	$(Q)$(ECHO) "Linking    $(subst $(TARGETDIR)/,,$(LINKTARGET))..."
 	$(Q)$(eval LINKTMPFILE=%(objdir)/$(notdir $(LINKTARGET)))
-	$(Q)$(IF) %(cmd) %(ldopts) %(from) -o $(LINKTMPFILE) %(ldflags) %(libs) 2>&1 > $(GENDIR)/cerrors 2>&1 ; then \
+	$(Q)$(IF) %(cmd) %(ldopts) %(from) -o $(LINKTMPFILE) %(ldflags) $(strip %(libs) %(archlibs)) 2>&1 > $(GENDIR)/cerrors 2>&1 ; then \
 		$(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
-				$(ECHO) "$(LINKTARGET): %(cmd) %(ldopts) %(from) -o $(LINKTARGET) %(ldflags) %(libs)" >> $(GENDIR)/errors ; \
+				$(ECHO) "$(LINKTARGET): %(cmd) %(ldopts) %(from) -o $(LINKTARGET) %(ldflags) $(strip %(libs) %(archlibs))" >> $(GENDIR)/errors ; \
 				$(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
 		else \
 			$(NOP) ; \
 		fi ; \
 		$(CP) $(LINKTMPFILE) $(LINKTARGET) ; \
 	else \
-		$(ECHO) "Link failed: %(cmd) %(ldopts) %(from) -o $(LINKTARGET) %(ldflags) %(libs)" 1>&2 ; \
+		$(ECHO) "Link failed: %(cmd) %(ldopts) %(from) -o $(LINKTARGET) %(ldflags) $(strip %(libs) %(archlibs))" 1>&2 ; \
 		tee < $(GENDIR)/cerrors -a $(GENDIR)/errors 1>&2 ; \
 		exit 1 ; \
 	fi
@@ -122,15 +122,15 @@ endif
 # Link a module based upon a number of arguments and the standard $(LIBS)
 # and $(DEPLIBS) make variables.
 #
-%define link_module_q cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" ldopts="$(strip $(TARGET_ISA_LDFLAGS) $(NOSTARTUP_LDFLAGS))" err="$(notdir $@).err" strip="$(STRIP)" stripdebug="$(DEBUG)" objs=/A endtag= module="$(MODULE)" ldflags="$(LDFLAGS)" libs="$(LIBS)" objdir="$(OBJDIR)"
-	$(Q)$(ECHO) "Building   $(subst $(TARGETDIR)/,,$@) ..."
+%define link_module_q cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" ldopts="$(strip $(TARGET_ISA_LDFLAGS) $(NOSTARTUP_LDFLAGS))" err="$(notdir $@).err" strip="$(STRIP)" stripdebug="$(DEBUG)" objs=/A endtag= module="$(MODULE)" ldflags="$(LDFLAGS)" libs="$(LIBS)" archlibs= objdir="$(OBJDIR)"
+	$(Q)$(ECHO) "Building Module  $(subst $(TARGETDIR)/,,$@) ..."
 	$(Q)$(IF) %(cmd) %(ldopts) $(NOSTARTUP_OBJECTS) \
 		$(GENMAP) %(objdir)/%(module).map \
-		%(objs) %(endtag) -o $@ %(ldflags) -Wl,--start-group %(libs) -Wl,--end-group 2>&1 > %(objdir)/%(err) 2>&1 ; \
+		%(objs) %(endtag) -o $@ %(ldflags) -Wl,--start-group $(strip %(libs) %(archlibs)) -Wl,--end-group 2>&1 > %(objdir)/%(err) 2>&1 ; \
 	then \
 		cat %(objdir)/%(err); \
 	else \
-		$(ECHO) "%(cmd) $(strip %(ldopts) $(GENMAP) %(objdir)/%(module).map %(objs) %(endtag) -o $@ %(ldflags) -Wl,--start-group %(libs) -Wl,--end-group)"; \
+		$(ECHO) "%(cmd) $(strip %(ldopts) $(GENMAP) %(objdir)/%(module).map %(objs) %(endtag) -o $@ %(ldflags) -Wl,--start-group $(strip %(libs) %(archlibs)) -Wl,--end-group)"; \
 		cat %(objdir)/%(err); \
 		exit 1; \
 	fi
@@ -811,7 +811,11 @@ endif
 ifeq (%(compiler),target)
   %(mmake)_LINK ?= $(strip $(AROS_CXX) $(TARGET_SYSROOT))
   %(mmake)_LD_OPTS ?= $(TARGET_ISA_LDFLAGS)
-  %(mmake)_LDFLAGS ?= $(strip $(TARGET_LDFLAGS))
+  %(mmake)_CXXLDFLAGS = $(strip $(USER_LDFLAGS) $(TARGET_LDFLAGS))
+ifneq ($(TARGET_LIBATOMIC),)
+  %(mmake)_ARCHLIBS += $(TARGET_CXX_LIBS)
+endif
+  %(mmake)_LDFLAGS ?= $(%(mmake)_CXXLDFLAGS)
   %(mmake)_STRIP ?= $(TARGET_STRIP)
   %(mmake)_ASSEMBLER ?= $(strip $(TARGET_CC) $(TARGET_SYSROOT))
   %(mmake)_CXXCMD:=$(strip $(AROS_CXX) $(TARGET_SYSROOT))
@@ -825,7 +829,11 @@ ifeq (%(compiler),kernel)
   KERNEL_CXX ?= $(KERNEL_CC)
   %(mmake)_LINK ?= $(strip $(KERNEL_CXX) $(KERNEL_SYSROOT) $(KERNEL_ISA_LDFLAGS))
   %(mmake)_LD_OPTS ?= $(KERNEL_ISA_LDFLAGS)
-  %(mmake)_LDFLAGS ?= $(strip $(USER_LDFLAGS) $(KERNEL_LDFLAGS))
+  %(mmake)_CXXLDFLAGS = $(strip $(USER_LDFLAGS) $(KERNEL_LDFLAGS))
+ifneq ($(TARGET_LIBATOMIC),)
+  %(mmake)_ARCHLIBS += $(TARGET_CXX_LIBS)
+endif
+  %(mmake)_LDFLAGS ?= $(%(mmake)_CXXLDFLAGS)
   %(mmake)_STRIP ?= $(ECHO) >/dev/null
   %(mmake)_ASSEMBLER ?= $(strip $(KERNEL_CC) $(KERNEL_SYSROOT))
   %(mmake)_CXXCMD:=$(strip $(KERNEL_CXX) $(KERNEL_SYSROOT))
@@ -1060,8 +1068,8 @@ $(%(mmake)-MA_TARGETS) : $(%(mmake)-MA_WILDCARD).o : %%(suffix)
 
 #------------------------------------------------------------------------------
 # Link %(objs) to %(prog) using the libraries in %(uselibs)
-%define rule_link_prog mmake=TMP prog=/A objs=/A ldflags="$(LDFLAGS)" uselibs= \
-    usehostlibs= usestartup=yes detach=no nix=no  \
+%define rule_link_prog mmake=TMP prog=/A objs=/A ldflags="$(LDFLAGS)" \
+    uselibs= usehostlibs= archlibs= usestartup=yes detach=no nix=no  \
     cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" ldopts="$(TARGET_ISA_LDFLAGS)" \
     strip="$(TARGET_STRIP)" stripdebug="$(DEBUG)" objdir="$(GENDIR)/$(CURDIR)" \
     coverageinstr="$(TARGET_COVERAGEINSTR)"
@@ -1105,7 +1113,7 @@ endif
 %(prog) : LDFLAGS := $(strip %(ldflags))
 %(prog) : LIBS := $(addprefix -l,%(uselibs) $(%(mmake)-link_EXTRA_LIBS) %(usehostlibs))
 %(prog) : %(objs) $(%(mmake)-link_DEPLIBS)
-	%link_q cmd="%(cmd)" ldopts="$(strip %(ldopts) $(%(mmake)-link_LD_OPTS))" strip="%(strip)" stripdebug="%(stripdebug)" from="$(OBJS)" ldflags="$(LDFLAGS)" libs="$(LIBS)" objdir="$(OBJDIR)" coverageinstr="%(coverageinstr)"
+	%link_q cmd="%(cmd)" ldopts="$(strip %(ldopts) $(%(mmake)-link_LD_OPTS))" strip="%(strip)" stripdebug="%(stripdebug)" from="$(OBJS)" ldflags="$(LDFLAGS)" libs="$(LIBS)" archlibs="%(archlibs)" objdir="$(OBJDIR)" coverageinstr="%(coverageinstr)"
 %end
 #------------------------------------------------------------------------------
 
@@ -1114,7 +1122,7 @@ endif
 # Link %(progs) from object in %(objdir) to executables in %(targetdir) using
 # the AROS libraries in %(uselibs) and the host libraries in %(usehostlibs)
 %define rule_link_progs mmake=TMP progs=/A targetdir="$(AROSDIR)/$(CURDIR)" nix="%(nix)" \
-    objdir="$(GENDIR)/$(CURDIR)" ldflags="$(LDFLAGS)" uselibs= usehostlibs= \
+    objdir="$(GENDIR)/$(CURDIR)" ldflags="$(LDFLAGS)" uselibs= usehostlibs= archlibs= \
     cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" ldopts="$(strip $(TARGET_ISA_LDFLAGS))" \
     strip="$(TARGET_STRIP)" stripdebug="$(DEBUG)" coverageinstr="$(TARGET_COVERAGEINSTR)" \
     usestartup=yes detach=no 
@@ -1152,7 +1160,7 @@ $(%(mmake)-link_PROGS) : OBJDIR := %(objdir)
 $(%(mmake)-link_PROGS) : LDFLAGS := $(strip %(ldflags))
 $(%(mmake)-link_PROGS) : LIBS := $(addprefix -l,%(uselibs) $(%(mmake)-link_EXTRA_LIBS) %(usehostlibs))
 $(%(mmake)-link_PROGS) : %(targetdir)/% : %(objdir)/%.o $(%(mmake)-link_DEPLIBS)
-	%link_q cmd="%(cmd)" ldopts="$(strip %(ldopts) $(%(mmake)-link_LD_OPTS))" strip="%(strip)" stripdebug="%(stripdebug)" from="$<" ldflags="$(LDFLAGS)" libs="$(LIBS)" objdir="$(OBJDIR)" coverageinstr="%(coverageinstr)"
+	%link_q cmd="%(cmd)" ldopts="$(strip %(ldopts) $(%(mmake)-link_LD_OPTS))" strip="%(strip)" stripdebug="%(stripdebug)" from="$<" ldflags="$(LDFLAGS)" libs="$(LIBS)" archlibs="%(archlibs)" objdir="$(OBJDIR)" coverageinstr="%(coverageinstr)"
 %end
 #------------------------------------------------------------------------------
 
@@ -1185,7 +1193,7 @@ endif
 %define rule_linkmodule mmake=TMP module=/A objs=/A endobj=/A err=/A objdir="$(OBJDIR)" \
     cmd="$(strip $(AROS_CC) $(TARGET_SYSROOT))" stripdebug="$(DEBUG)" \
     ldopts="$(strip $(TARGET_ISA_LDFLAGS) $(NOSTARTUP_LDFLAGS))" ldflags="$(LDFLAGS)" \
-    uselibs= usehostlibs=
+    uselibs= usehostlibs= archlibs=
 
 %(mmake)_LDFLAGS  := %(ldflags)
 # Make a list of the lib files the programs depend on.
@@ -1219,7 +1227,7 @@ else
                     -L/usr/lib $(addprefix -l,%(usehostlibs))
 endif 
 %(module) : %(objs) %(endobj) $(%(mmake)_DEPLIBS) $(USER_DEPLIBS)
-	%link_module_q cmd="%(cmd)" ldopts="%(ldopts)" err="$(ERR)" endtag="$(ENDTAG)" objs="$(OBJS)" libs="$(LIBS)" objdir="$(OBJDIR)" ldflags="$(LDFLAGS)" stripdebug="%(stripdebug)"
+	%link_module_q cmd="%(cmd)" ldopts="%(ldopts)" err="$(ERR)" endtag="$(ENDTAG)" objs="$(OBJS)" libs="$(LIBS)" archlibs="%(archlibs)" objdir="$(OBJDIR)" ldflags="$(LDFLAGS)" stripdebug="%(stripdebug)"
 
 %end
 #------------------------------------------------------------------------------
@@ -1777,6 +1785,13 @@ KERNEL_CXX ?= $(strip $(KERNEL_CC) $(KERNEL_SYSROOT))
 endif
 endif
 
+ifeq (%(compiler),target)
+%(mmake)_ARCHLIBS += $(TARGET_C_LIBS)
+endif
+ifeq (%(compiler),kernel)
+%(mmake)_ARCHLIBS += $(TARGET_C_LIBS)
+endif
+
 %(mmake)_STRIPDEBUG ?= $(DEBUG)
 
 ifneq ($(filter $(TARGET),%(mmake) %(mmake)-quick %(mmake)-gz-quick),)
@@ -1798,7 +1813,7 @@ ifneq ($(filter $(TARGET),%(mmake) %(mmake)-quick %(mmake)-gz-quick),)
 
 %rule_link_prog mmake=%(mmake) prog="$(%(mmake)_TARGETDIR)/$(%(mmake)_PROGNAME)" \
     objs="$(%(mmake)_OBJS) $(%(mmake)_ARCHOBJS) $(USER_OBJS)" ldflags="$(%(mmake)_LDFLAGS)" \
-    uselibs="$(%(mmake)_LIBS)" usehostlibs="%(usehostlibs)" \
+    uselibs="$(%(mmake)_LIBS)" usehostlibs="%(usehostlibs)" archlibs="$(%(mmake)_ARCHLIBS)"\
     usestartup="%(usestartup)" detach="%(detach)" nix="%(nix)" \
     cmd="$(%(mmake)_LINK)" ldopts="$(%(mmake)_LD_OPTS)" \
     strip="$(%(mmake)_STRIP)" stripdebug="$(%(mmake)_STRIPDEBUG)" \
@@ -1851,7 +1866,9 @@ ifneq (%(includedir),)
 endif
 %(mmake)_CFLAGS    := %(cflags)
 %(mmake)_COVERAGE := no
+
 ifeq (%(compiler),target)
+%(mmake)_ARCHLIBS := $(TARGET_C_LIBS)
 ifeq (%(usestartup),yes)
 ifeq (%(coverageinstr),yes)
 %(mmake)_COVERAGE := yes
@@ -1913,7 +1930,7 @@ ifneq ($(filter $(TARGET),%(mmake) %(mmake)-quick),)
 %rule_link_progs mmake=%(mmake) progs="$(%(mmake)_FILES)" nix="%(nix)" \
     targetdir="$(%(mmake)_TARGETDIR)" objdir="$(%(mmake)_OBJDIR)" \
     ldflags="$(%(mmake)_LDFLAGS)" \
-    uselibs="$(%(mmake)_LIBS)" usehostlibs="%(usehostlibs)" \
+    uselibs="$(%(mmake)_LIBS)" usehostlibs="%(usehostlibs)" archlibs="$(%(mmake)_ARCHLIBS)" \
     usestartup="%(usestartup)" detach="%(detach)" \
     cmd="$(%(mmake)_LINK)" ldopts="$(%(mmake)_LD_OPTS)" strip="$(%(mmake)_STRIP)" objdir="$(%(mmake)_OBJDIR)" coverageinstr="$(%(mmake)_COVERAGE)"
 
@@ -1974,6 +1991,7 @@ endif
 %(mmake)_LDFLAGS += $(strip $(HOST_LDFLAGS))
 endif
 ifeq (%(compiler),target)
+%(mmake)_ARCHLIBS := $(TARGET_C_LIBS)
 ifeq (%(alwayscxxlink),yes)
 %(mmake)_LINK= $(strip $(AROS_CXX) $(TARGET_ISA_LDFLAGS) $(TARGET_SYSROOT))
 endif
@@ -2107,7 +2125,7 @@ endif
 %rule_linkmodule module="$(%(mmake)_MODULE)" objs="$(%(mmake)_OBJS)" \
     endobj= err="$(%(mmake)_ERR)" objdir="%(objdir)" \
     cmd="$(%(mmake)_LINK)" ldopts="$(%(mmake)_LD_OPTS)" ldflags="$(strip $(LDFLAGS) $(%(mmake)_LDFLAGS) $(%(modname)_LDFLAGS))" \
-    uselibs="%(uselibs) $(%(modname)_LIBS)" usehostlibs="%(usehostlibs)" stripdebug="%(stripdebug)"
+    uselibs="%(uselibs) $(%(modname)_LIBS)" usehostlibs="%(usehostlibs)" archlibs="$(%(mmake)_ARCHLIBS)" stripdebug="%(stripdebug)"
 
 # Link kernel object file
 %(mmake)_KAUTOLIB := dos intuition layers graphics oop utility expansion keymap
@@ -2245,6 +2263,7 @@ ifneq (%(incextra),)
 else
 %(mmake)_INCEXTRA  := $(TOP)/$(CURDIR)/..
 endif
+
 ifeq (%(compiler),host)
 ifeq (%(alwayscxxlink),yes)
 %(mmake)_LINK= $(strip $(HOST_CXX) $(HOST_LDFLAGS))
@@ -2252,20 +2271,28 @@ endif
 %(mmake)_LD_OPTS := $(strip $(HOST_ISA_LDFLAGS) $(NOSTARTUP_LDFLAGS))
 %(mmake)_LDFLAGS += $(strip $(HOST_LDFLAGS))
 endif
+
 ifeq (%(compiler),target)
+%(mmake)_LDFLAGS = $(strip $(LDFLAGS))
 ifeq (%(alwayscxxlink),yes)
 %(mmake)_LINK= $(strip $(AROS_CXX) $(TARGET_SYSROOT))
+ifneq ($(TARGET_CXX_LIBS),)
+%(mmake)_ARCHLIBS := $(TARGET_CXX_LIBS)
+endif
 endif
 %(mmake)_LD_OPTS := $(strip $(TARGET_ISA_LDFLAGS) $(NOSTARTUP_LDFLAGS))
-%(mmake)_LDFLAGS = $(strip $(LDFLAGS))
 endif
+
 ifeq (%(compiler),kernel)
+%(mmake)_LDFLAGS := $(strip $(USER_LDFLAGS) $(KERNEL_LDFLAGS))
 ifeq (%(alwayscxxlink),yes)
 KERNEL_CXX ?= $(strip $(KERNEL_CC))
 %(mmake)_LINK= $(strip $(KERNEL_CXX) $(KERNEL_SYSROOT))
+ifneq ($(TARGET_LIBATOMIC),)
+%(mmake)_ARCHLIBS := $(TARGET_CXX_LIBS)
+endif
 endif
 %(mmake)_LD_OPTS := $(strip $(KERNEL_ISA_LDFLAGS) $(NOSTARTUP_LDFLAGS))
-%(mmake)_LDFLAGS := $(strip $(USER_LDFLAGS) $(KERNEL_LDFLAGS))
 endif
 
 # Default values for variables and arguments
@@ -2636,11 +2663,18 @@ $(%(mmake)%(flavour)_DEFNAME)_LDFLAGS = $(%(mmake)_LDFLAGS)
 $(%(mmake)%(flavour)_DEFNAME)_STRIPDEBUG ?= %(stripdebug)
 
 ifeq (%(build_library),M)
+
+ifeq (%(compiler),target)
+%(mmake)_ARCHLIBS += $(TARGET_C_LIBS)
+endif
+ifeq (%(compiler),kernel)
+%(mmake)_ARCHLIBS += $(TARGET_C_LIBS)
+endif
 # The module is linked from all the compiled .o files
 %rule_linkmodule module="$(%(mmake)%(flavour)_MODULE)" objs="$(%(mmake)%(flavour)_STARTOBJS) $(%(mmake)%(flavour)_OBJS) $(USER_OBJS)" \
 		 endobj="$(%(mmake)%(flavour)_ENDOBJS)" err="$(%(mmake)%(flavour)_ERR)" objdir="$(%(mmake)%(flavour)_OBJDIR)" \
 		 cmd="$(%(mmake)%(flavour)_LINK)" ldopts="$(%(mmake)_LD_OPTS)" ldflags="$($(%(mmake)%(flavour)_DEFNAME)_LDFLAGS)" \
-		 uselibs="$(%(mmake)%(flavour)_LIBS) $($(%(mmake)%(flavour)_DEFNAME)_LIBS)" usehostlibs="%(usehostlibs)" stripdebug="$($(%(mmake)%(flavour)_DEFNAME)_STRIPDEBUG)"
+		 uselibs="$(%(mmake)%(flavour)_LIBS) $($(%(mmake)%(flavour)_DEFNAME)_LIBS)" usehostlibs="%(usehostlibs)" archlibs="$(%(mmake)_ARCHLIBS)" stripdebug="$($(%(mmake)%(flavour)_DEFNAME)_STRIPDEBUG)"
 endif
 
 ifeq (%(build_abi),M)
