Print the error message if compile/link fails
git-svn-id: https://svn.aros.org/svn/aros/trunk@7336 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/config/make.tmpl b/config/make.tmpl
--- a/config/make.tmpl
+++ b/config/make.tmpl
@@ -44,13 +44,14 @@
 	@$(ECHO) "Compiling %(path)%(from)..."
 	@$(IF) %(cmd) %(opt) -c %(from) -o %(to) > $(GENDIR)/cerrors 2>&1 ; then \
 	    $(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
-		echo "%(path)%(from): %(cmd) %(opt) -c %(from) -o %(to)" >> $(GENDIR)/errors ; \
-		cat $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
+		$(ECHO) "%(path)%(from): %(cmd) %(opt) -c %(from) -o %(to)" >> $(GENDIR)/errors ; \
+		$(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
 	    else \
 		true ; \
 	    fi ; \
 	else \
-	    echo "Compile failed: %(cmd) %(opt) -c %(from) -o %(to)" ; \
+	    $(ECHO) "Compile failed: %(cmd) %(opt) -c %(from) -o %(to)" 1>&2 ; \
+	    $(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors 1>&2 ; \
 	    exit 1 ; \
 	fi
 %end
@@ -60,13 +61,14 @@
 	@$(ECHO) "Linking %(to)..."
 	@$(IF) %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs) 2>&1 > $(GENDIR)/cerrors 2>&1 ; then \
 	    $(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
-		echo "%(path)%(from): %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" >> $(GENDIR)/errors ; \
-		cat $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
+		$(ECHO) "%(path)%(from): %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" >> $(GENDIR)/errors ; \
+		$(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
 	    else \
 		true ; \
 	    fi ; \
 	else \
-	    echo "Link failed: %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" ; \
+	    $(ECHO) "Link failed: %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" 1>&2 ; \
+	    $(CAT) $(GENDIR)/cerrors 1>&2 ; \
 	    exit 1 ; \
 	fi
 %checkuds to=%(to) linkcmd="%(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)"
@@ -394,7 +396,7 @@ ALL_OBJS := $(SYS_OBJS) $(OBJS) $(ENDFUNC)
 
 $(OSMODDIR)/$(OSMODULE) : $(LIB) $(INITFUNC) \
 	    $(foreach f,$(DEPLIBS), $(LIBDIR)/lib$(f).a)
-	@echo "Building $(notdir $@) ..."
+	@$(ECHO) "Building $(notdir $@) ..."
 	@$(CC) $(ILDFLAGS) $(GENMAP) $(OSMODULE).map -L$(LIBDIR) \
 	    $(INITFUNC) $(LIB) $(foreach f, $(DEPLIBS), -l$(f)) \
 	    -o $@ 2>&1 | tee $(OSMODULE).err
@@ -499,7 +501,7 @@ ALL_OBJS := $(SYS_OBJS) $(OBJS) $(OBJDIR)/functions.o $(ENDFUNC)
 
 $(OSMODDIR)/$(OSMODULE) : $(LIB) $(INITFUNC) \
 	    $(foreach f,$(DEPLIBS), $(LIBDIR)/lib$(f).a)
-	@echo "Building $(notdir $@) ..."
+	@$(ECHO) "Building $(notdir $@) ..."
 	@%(cc) $(ILDFLAGS) $(GENMAP) $(OSMODULE).map -L$(LIBDIR) \
 	    $(INITFUNC) $(LIB) $(foreach f, $(DEPLIBS), -l$(f)) \
 	    -o $@ 2>&1 | tee $(OSMODULE).err
@@ -602,7 +604,7 @@ ALL_OBJS := $(SYS_OBJS) $(OBJS) $(OBJDIR)/functions.o $(ENDFUNC)
 
 $(OSMODDIR)/$(OSMODULE) : $(LIB) $(INITFUNC) \
 	    $(foreach f,$(DEPLIBS), $(LIBDIR)/lib$(f).a)
-	@echo "Building $(notdir $@) ..."
+	@$(ECHO) "Building $(notdir $@) ..."
 	@%(cc) $(ILDFLAGS) $(GENMAP) $(OSMODULE).map -L$(LIBDIR) \
 	    $(INITFUNC) $(LIB) $(foreach f, $(DEPLIBS), -l$(f)) \
 	    -o $@ 2>&1 | tee $(OSMODULE).err
@@ -709,7 +711,7 @@ ALL_OBJS := $(SYS_OBJS) $(OBJS) $(OBJDIR)/functions.o $(ENDFUNC)
 
 $(OSMODDIR)/$(OSMODULE) : $(LIB) $(INITFUNC) \
 	    $(foreach f,$(DEPLIBS), $(LIBDIR)/lib$(f).a)
-	@echo "Building $(notdir $@) ..."
+	@$(ECHO) "Building $(notdir $@) ..."
 	@%(cc) $(ILDFLAGS) $(GENMAP) $(OSMODULE).map -L$(LIBDIR) \
 	    $(INITFUNC) $(LIB) $(foreach f, $(DEPLIBS), -l$(f)) \
 	    -o $@ 2>&1 | tee $(OSMODULE).err
