Greatly simplified mmakefiles which generate libs. *WARNING* This breaks makefiles which use %genlib !!
Show flags only if target is built (not in setup).


git-svn-id: https://svn.aros.org/svn/aros/trunk@3055 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/config/make.tmpl b/config/make.tmpl
--- a/config/make.tmpl
+++ b/config/make.tmpl
@@ -127,15 +127,14 @@ DEPLIBS = $(LIBDIR)/libamiga.a $(LIBDIR)/libarossupport.a $(STARTUP) \
 
 # Prepare creation of a shared lib
 %define prepare_shlib lib=dummy shflag=$(SHARED_DUMMY)
-OBJDIR=$(OSGENDIR)/%(lib)
 ifeq ("%(shflag)","yes")
-LIB=$(LIBDIR)/lib%(lib).so
-RMLIB=$(LIBDIR)/lib%(lib).a
-AR=$(SHARED_AR)
-RANLIB=$(NOP)
+LIB    := $(LIBDIR)/lib%(lib).so
+RMLIB  := $(LIBDIR)/lib%(lib).a
+AR     := $(SHARED_AR)
+RANLIB := $(NOP)
 else
-LIB=$(LIBDIR)/lib%(lib).a
-RMLIB=$(LIBDIR)/lib%(lib).so
+LIB    := $(LIBDIR)/lib%(lib).a
+RMLIB  := $(LIBDIR)/lib%(lib).so
 endif
 %end
 
@@ -187,25 +186,7 @@ endif
 	@$(AWK) -f %(script) $< > $@
 %end
 
-# Rule to create a .library in the local dir
-%define genlib
-libdefs.h : lib.conf $(BINDIR)/scripts/genlibdefs.awk
-	@$(ECHO) "Generating $@..."
-	@$(AWK) -f $(BINDIR)/scripts/genlibdefs.awk $< > $@
-
-FUNCTABLE_SRCS := $(foreach f,$(FUNCTIONS),$(f).c)
-
-functable.c : $(FUNCTABLE_SRCS) $(BINDIR)/scripts/genfunctable.awk \
-	    libdefs.h
-	@$(ECHO) "Generating $@..."
-	@$(AWK) -f $(BINDIR)/scripts/genfunctable.awk $(FUNCTABLE_SRCS) > $@
-
-endtag.c :
-	@$(ECHO) "Generating $@..."
-	@$(ECHO) "#include <libcore/libtail.c>" > $@
-%end
-
-%define genlib_old dest=libdefs.h flags=$(CFLAGS) from=$< to=$@ dir=$(@D) opt= cc=$(CC)
+%define genlib_old flags=$(CFLAGS) cc=$(CC)
 ifndef SLIB
 SLIB := $(SLIBDIR)/$(LIBNAME).library
 endif
@@ -281,10 +262,10 @@ setup :
 	done
 
 clean ::
-	$(RM) $(OBJDIR) *.err
+	$(RM) $(OBJDIR) *.err libdefs.h $(LIBNAME)_functable.c $(LIBNAME)_endtag.c
 
 $(OBJDIR)/%.o : %.c
-	@$(ECHO) "Compiling $(CURDIR)/%(from)..."
+	@$(ECHO) "Compiling $(CURDIR)/$<..."
 	@%(cc) %(flags) -c $< -o $@ 2>&1|tee $*.err
 	@$(IF) $(TEST) -s $*.err ; then $(TOUCH) $(TOP)/errors ; else $(RM) $*.err ; fi
 
@@ -304,6 +285,202 @@ $(OBJDIR)/$(LIBNAME)_init.o : libdefs.h
 libdefs.h : lib.conf $(GENLIBDEF_SCRIPT)
 	@$(ECHO) "Generating $@..."
 	@$(AWK) -f $(GENLIBDEF_SCRIPT) $< > $@
+
+$(OBJDIR)/%.d : %.c
+	@$(IF) [ ! -d $(@D) ]; then $(MKDIR) $(@D) ; else $(NOP) ; fi
+	@$(ECHO) "Makedepend $(CURDIR)/$<..."
+	@$(MKDEPEND) -f- -p$(@D)/ $(MKDEPEND_FLAGS) -- $(CFLAGS) -- $< > $@
+%end
+
+%define genlib flags=$(CFLAGS) cc=$(CC)
+ifndef SLIB
+SLIB := $(SLIBDIR)/$(LIBNAME).library
+endif
+ifndef LIB
+LIB := $(LIBDIR)/lib$(LIBNAME).a
+endif
+ifndef INIT_FILE
+INIT_FILE := $(LIBNAME)_init
+endif
+ifndef END_FILE
+END_FILE := endtag
+endif
+ifndef OBJDIR
+OBJDIR := $(GENDIR)/$(CURDIR)
+endif
+ifndef GENLIBDEF_SCRIPT
+GENLIBDEF_SCRIPT := $(TOP)/scripts/genlibdefs.gawk
+endif
+ifndef INITFUNC
+INITFUNC := $(OBJDIR)/$(INIT_FILE).o
+endif
+ifndef ENDFUNC
+ENDFUNC := $(OBJDIR)/$(END_FILE).o
+endif
+SYS_FILES := $(SYS_FILES) $(INIT_FILE) functable
+ifndef OBJS
+OBJS := $(foreach f,$(FILES) $(FUNCTIONS) $(ADDITIONAL_OBJS),$(OBJDIR)/$(f).o)
+endif
+SYS_OBJS := $(foreach f,$(SYS_FILES),$(OBJDIR)/$(f).o)
+
+# ***** Native ***************
+ifeq ($(FLAVOUR),native)
+
+# Generate a map file
+MAPGEN	:= -Xlinker -M
+
+# Strip resulting binary
+STRIP	:= strip
+
+# ***** Not Native ***************
+else
+
+MAPGEN	:=
+STRIP	:= $(NOP)
+
+# ***** END ***************
+endif
+
+$(SLIB) : $(LIB) $(DEPLIBS) $(EXTRA_DEPLIBS) $(OBJS) $(SYS_OBJS) $(ENDFUNC)
+	@$(ECHO) "Building $(notdir $@) ..."
+	@$(CC) $(ILDFLAGS) $(MAPGEN) $(SYS_OBJS) $(EXTRA_LIBS) $(LIBS) $(ENDFUNC) -o $@ 2>&1|tee $(LIBNAME)lib.map
+	@$(ECHO) "Checking $@..."
+	@$(CHECKUDS) $@ > undefdsyms.list
+	@$(IF) $(TEST) -s undefdsyms.list ; then \
+	    $(CAT) undefdsyms.list >> $(@F)-x.err ; \
+	    $(ECHO) "There are undefined symbols in $@:" ; \
+	    $(CAT) undefdsyms.list ; \
+	else $(NOP) ; fi
+	@$(RM) undefdsyms.list
+	@$(IF) $(TEST) ! -s $(LIBNAME)lib.map; then $(RM) $(LIBNAME)lib.map ; else $(NOP) ; fi
+	@$(STRIP) $@
+
+# Collect all functions in a linklib for fast linking:
+$(LIB) : $(OBJS)
+	@$(ECHO) "Adding functions to $(notdir $@) ..."
+	@$(AR) $@ $?
+	@$(RANLIB) $@
+
+show-flags :
+	@$(ECHO) "CFLAGS=$(CFLAGS)"
+
+setup :
+	@$(FOR) dir in $(OBJDIR) $(LIBDIR) $(SLIBDIR) $(DESTDIRS) ; do \
+	    $(IF) $(TEST) ! -d $$dir ; then $(MKDIR) $$dir ; else $(NOP) ; fi ; \
+	done
+
+clean ::
+	$(RM) $(OBJDIR) *.err libdefs.h functable.c endtag.c $(EXTRA_CLEAN) \
+	    $(LIB) $(SLIB)
+
+$(OBJDIR)/%.o : %.c
+	@$(ECHO) "Compiling $(CURDIR)/$<..."
+	@%(cc) %(flags) -c $< -o $@ 2>&1|tee $*.err
+	@$(IF) $(TEST) -s $*.err ; then $(TOUCH) $(TOP)/errors ; else $(RM) $*.err ; fi
+
+# Rule to create a .library in the local dir
+libdefs.h : lib.conf $(BINDIR)/scripts/genlibdefs.awk
+	@$(ECHO) "Generating $@..."
+	@$(AWK) -f $(BINDIR)/scripts/genlibdefs.awk $< > $@
+
+FUNCTABLE_SRCS := $(foreach f,$(FUNCTIONS),$(f).c)
+
+functable.c : $(FUNCTABLE_SRCS) $(BINDIR)/scripts/genfunctable.awk \
+	    libdefs.h
+	@$(ECHO) "Generating $@..."
+	@$(AWK) -f $(BINDIR)/scripts/genfunctable.awk $(FUNCTABLE_SRCS) > $@
+
+endtag.c :
+	@$(ECHO) "Generating $@..."
+	@$(ECHO) "#include <libcore/libtail.c>" > $@
+
+$(OBJDIR)/$(LIBNAME)_init.o : libdefs.h
+
+ifneq (,$(ADDITIONAL_OBJS))
+$(foreach f,$(ADDITIONAL_OBJS),$(OBJDIR)/$(f).o) :
+	@$(ECHO) "Error: The precompiled object $@ did not exist."
+	@exit 1
+endif
+
+$(OBJDIR)/%.d : %.c
+	@$(IF) [ ! -d $(@D) ]; then $(MKDIR) $(@D) ; else $(NOP) ; fi
+	@$(ECHO) "Makedepend $(CURDIR)/$<..."
+	@$(MKDEPEND) -f- -p$(@D)/ $(MKDEPEND_FLAGS) -- $(CFLAGS) -- $< > $@
+%end
+
+%define genromlib flags=$(CFLAGS) cc=$(CC)
+ifndef INIT_FILE
+INIT_FILE := $(LIBNAME)_init
+endif
+ifndef END_FILE
+END_FILE := endtag
+endif
+ifndef OBJDIR
+OBJDIR := $(GENDIR)/$(CURDIR)
+endif
+ifndef GENLIBDEF_SCRIPT
+GENLIBDEF_SCRIPT := $(TOP)/scripts/genlibdefs.gawk
+endif
+ifndef INITFUNC
+INITFUNC := $(OBJDIR)/$(INIT_FILE).o
+endif
+ifndef ENDFUNC
+ENDFUNC := $(OBJDIR)/$(END_FILE).o
+endif
+SYS_FILES := $(SYS_FILES) $(INIT_FILE) functable
+ifndef OBJS
+OBJS := $(foreach f,$(FILES) $(FUNCTIONS) $(ADDITIONAL_OBJS),$(OBJDIR)/$(f).o)
+endif
+SYS_OBJS := $(foreach f,$(SYS_FILES),$(OBJDIR)/$(f).o)
+
+ALL_OBJS := $(SYS_OBJS) $(OBJS) $(ENDFUNC)
+
+# Collect all functions in a linklib for fast linking:
+$(LIB) : $(ALL_OBJS)
+	@$(ECHO) "Creating library $@..."
+	@$(AR) $@ $(ALL_OBJS)
+	@$(RANLIB) $@
+
+show-flags :
+	@$(ECHO) "CFLAGS=$(CFLAGS)"
+
+setup :
+	@$(FOR) dir in $(OBJDIR) $(LIBDIR) $(SLIBDIR) $(DESTDIRS) ; do \
+	    $(IF) $(TEST) ! -d $$dir ; then $(MKDIR) $$dir ; else $(NOP) ; fi ; \
+	done
+
+clean ::
+	$(RM) $(OBJDIR) *.err libdefs.h functable.c endtag.c $(EXTRA_CLEAN) \
+	    $(LIB) $(SLIB)
+
+$(OBJDIR)/%.o : %.c
+	@$(ECHO) "Compiling $(CURDIR)/$<..."
+	@%(cc) %(flags) -c $< -o $@ 2>&1|tee $*.err
+	@$(IF) $(TEST) -s $*.err ; then $(TOUCH) $(TOP)/errors ; else $(RM) $*.err ; fi
+
+# Rule to create a .library in the local dir
+libdefs.h : lib.conf $(BINDIR)/scripts/genlibdefs.awk
+	@$(ECHO) "Generating $@..."
+	@$(AWK) -f $(BINDIR)/scripts/genlibdefs.awk $< > $@
+
+FUNCTABLE_SRCS := $(foreach f,$(FUNCTIONS),$(f).c)
+
+functable.c : $(FUNCTABLE_SRCS) $(BINDIR)/scripts/genfunctable.awk \
+	    libdefs.h
+	@$(ECHO) "Generating $@..."
+	@$(AWK) -f $(BINDIR)/scripts/genfunctable.awk $(FUNCTABLE_SRCS) > $@
+
+endtag.c :
+	@$(ECHO) "Generating $@..."
+	@$(ECHO) "#include <libcore/libtail.c>" > $@
+
+$(OBJDIR)/$(LIBNAME)_init.o : libdefs.h
+
+ifneq (,$(ADDITIONAL_OBJS))
+$(foreach f,$(ADDITIONAL_OBJS),$(OBJDIR)/$(f).o) :
+	@$(ECHO) "Error: The precompiled object $@ did not exist."
+	@exit 1
+endif
 
 $(OBJDIR)/%.d : %.c
 	@$(IF) [ ! -d $(@D) ]; then $(MKDIR) $(@D) ; else $(NOP) ; fi
