Added support for gensets. I've tested it enough, I think, so it shouldn't break anything, but if it does, please don't blame me too much :)
git-svn-id: https://svn.aros.org/svn/aros/trunk@10618 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/config/make.tmpl b/config/make.tmpl
--- a/config/make.tmpl
+++ b/config/make.tmpl
@@ -70,17 +70,39 @@
 %define link_q cmd=$(CC) opt=$(ILDFLAGS) startup=$(STARTUP) from=$< to=$@ libs=$(LIBS)
 	@$(ECHO) "Linking %(to)..."
 	@$(IF) %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs) 2>&1 > $(GENDIR)/cerrors 2>&1 ; then \
-	    $(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
-		$(ECHO) "%(to): %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" >> $(GENDIR)/errors ; \
-		$(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
-	    else \
-		$(NOP) ; \
-	    fi ; \
+		$(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
+				$(ECHO) "%(to): %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" >> $(GENDIR)/errors ; \
+				$(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
+	   	else \
+			$(NOP) ; \
+    	fi ; \
 	else \
 	    $(ECHO) "Link failed: %(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)" 1>&2 ; \
 	    tee < $(GENDIR)/cerrors -a $(GENDIR)/errors 1>&2 ; \
 	    exit 1 ; \
 	fi
+
+	@$(NM_PLAIN) %(to) | $(GENSETS) >%(to)_sets.c
+	@$(IF) $(TEST) -s %(to)_sets.c && $(CC) -c %(to)_sets.c -o %(to)_sets.o; then \
+		$(IF) %(cmd) %(opt) %(to) %(to)_sets.o -o %(to).tmp 2>&1 > $(GENDIR)/cerrors 2>&1 ; then \
+	    	$(IF) $(TEST) -s $(GENDIR)/cerrors ; then \
+				$(ECHO) "%(to).tmp: %(cmd) %(opt) %(to) %(to)_sets.o -o %(to).tmp" >> $(GENDIR)/errors ; \
+				$(CAT) $(GENDIR)/cerrors >> $(GENDIR)/errors ; \
+	    	else \
+				$(NOP) ; \
+	    	fi ; \
+		else \
+	    	$(ECHO) "Link failed: %(cmd) %(opt) %(to) %(to)_sets.o -o %(to).tmp" 1>&2 ; \
+	    	tee < $(GENDIR)/cerrors -a $(GENDIR)/errors 1>&2 ; \
+			$(RM) -f %(to) %(to)_sets.*; \
+			exit 1 ; \
+		fi; \
+		$(RM) %(to);\
+		$(MV) %(to).tmp %(to); \
+	fi
+
+	@$(RM) %(to)_sets.*
+
 %checkuds to=%(to) linkcmd="%(cmd) %(opt) %(startup) %(from) -o %(to) %(libs)"
 %end
 
