Use the same compiler for generating the dependency then during the compilation of the code.
git-svn-id: https://svn.aros.org/svn/aros/trunk@21652 fb15a70f-31f2-0310-bbcc-cdcc74a49acc

diff --git a/scripts/mkdep b/scripts/mkdep
--- a/scripts/mkdep
+++ b/scripts/mkdep
@@ -34,7 +34,12 @@ if [ "x$dest" = x ]; then
     exit 1
 fi
 
-CMD="gcc -M $args $files | sed 's#^.*\.o:#`dirname $dest`/&#'"
+if [ "x$AROS_CC" = x ]; then
+    echo "$0: Error: AROS_CC not defined"
+    exit 1
+fi
+
+CMD="$AROS_CC -M $args $files | sed 's#^.*\.o:#`dirname $dest`/&#'"
 #echo $CMD
 
 eval $CMD > $dest
